module.exports = [
  {
    id: 1,
    text: "In 2012, a man in Oregon was arrested for DUI while driving a ____.",
    answer: "Lawn Mower",
  },
  {
    id: 2,
    text: "The intense fear of ____ is known as 'Arachibutyrophobia'.",
    answer: "Peanut Butter",
  },
  {
    id: 3,
    text: "A company in Japan sells a doll that looks like ____.",
    answer: "Obama",
  },
  {
    id: 4,
    text: "In the 19th century, ketchup was sold as medicine to cure ____.",
    answer: "Diarrhea",
  },
  {
    id: 5,
    text: "The first item sold on eBay was a broken ____.",
    answer: "Laser Pointer",
  },
  {
    id: 6,
    text: "In 2013, a pig in Australia stole 18 beers from a campsite, got drunk, and fought a ____.",
    answer: "Cow",
  },
  {
    id: 7,
    text: "A 2009 study found that cows who have ____ produce more milk.",
    answer: "Names",
  },
  {
    id: 8,
    text: "The official state sport of Maryland is ____.",
    answer: "Jousting",
  },
  {
    id: 9,
    text: "Banging your head against a wall burns ____ calories an hour.",
    answer: "150",
  },
  {
    id: 10,
    text: "In Switzerland, it is illegal to own just one ____.",
    answer: "Guinea Pig",
  },
  { id: 11, text: "A group of pugs is called a ____.", answer: "Grumble" },
  {
    id: 12,
    text: "In 2015, a silver coin with the image of ____ was minted in New Zealand.",
    answer: "Pizza",
  },
  {
    id: 13,
    text: "The dot over the letter 'i' is called a ____.",
    answer: "Tittle",
  },
  {
    id: 14,
    text: "Before toilet paper was invented, Americans used ____.",
    answer: "Corn Cobs",
  },
  {
    id: 15,
    text: "A group of flamingos is called a ____.",
    answer: "Flamboyance",
  },
  {
    id: 16,
    text: "In 2014, a woman was arrested in Pennsylvania for shoplifting 50 bottles of ____.",
    answer: "Air Freshener",
  },
  {
    id: 17,
    text: "The inventor of the Pringles can is buried in a ____.",
    answer: "Pringles Can",
  },
  {
    id: 18,
    text: "In 1386, a pig in France was executed by public hanging for the murder of a ____.",
    answer: "Child",
  },
  {
    id: 19,
    text: "Human thigh bones are stronger than ____.",
    answer: "Concrete",
  },
  {
    id: 20,
    text: "The national animal of Scotland is the ____.",
    answer: "Unicorn",
  },
  {
    id: 21,
    text: "In 2006, an Australian man tried to sell ____ on eBay.",
    answer: "New Zealand",
  },
  {
    id: 22,
    text: "The tiny plastic piece at the end of a shoelace is called an ____.",
    answer: "Aglet",
  },
  {
    id: 23,
    text: "Coprastastaphobia is the fear of ____.",
    answer: "Constipation",
  },
  {
    id: 24,
    text: "In 1923, jockey Frank Hayes won a race at Belmont Park despite being ____.",
    answer: "Dead",
  },
  {
    id: 25,
    text: "The first webcam was invented to check the status of a ____.",
    answer: "Coffee Pot",
  },
  { id: 26, text: "A group of ferrets is called a ____.", answer: "Business" },
  {
    id: 27,
    text: "In 1998, Sony accidentally sold 700,000 camcorders that could see through ____.",
    answer: "Clothes",
  },
  {
    id: 28,
    text: "The fear of long words is called ____.",
    answer: "Hippopotomonstrosesquippedaliophobia",
  },
  {
    id: 29,
    text: "Billy goats urinate on their own ____ to attract females.",
    answer: "Heads",
  },
  {
    id: 30,
    text: "In 2011, a woman bought a non-visible piece of art for $10,000 made entirely of ____.",
    answer: "Air",
  },
  {
    id: 31,
    text: "The electric chair was invented by a ____.",
    answer: "Dentist",
  },
  {
    id: 32,
    text: "A duel between three people is called a ____.",
    answer: "Truel",
  },
  {
    id: 33,
    text: "In 2008, a man in Zimbabwe was arrested for 'criminal nuisance' after he was caught ____ at a police car.",
    answer: "Laughing",
  },
  {
    id: 34,
    text: "The King of Hearts is the only king without a ____.",
    answer: "Mustache",
  },
  {
    id: 35,
    text: "During WWII, the crew of a British submarine found a ____ inside a torpedo tube.",
    answer: "Reindeer",
  },
  {
    id: 36,
    text: "The Twitter bird's official name is ____.",
    answer: "Larry",
  },
  {
    id: 37,
    text: "In 2016, a man in Florida threw a ____ through a drive-thru window.",
    answer: "Alligator",
  },
  {
    id: 38,
    text: "A single strand of spaghetti is called a ____.",
    answer: "Spaghetto",
  },
  {
    id: 39,
    text: "The space between your eyebrows is called the ____.",
    answer: "Glabella",
  },
  {
    id: 40,
    text: "In 2012, a Swedish man was arrested for trying to split atoms in his ____.",
    answer: "Kitchen",
  },
  {
    id: 41,
    text: "The plastic thing inside a pizza box is called a ____.",
    answer: "Pizza Saver",
  },
  {
    id: 42,
    text: "A group of porcupines is called a ____.",
    answer: "Prickle",
  },
  {
    id: 43,
    text: "In 1907, an ad campaign for Corn Flakes offered a free ____ to anyone who bought a box.",
    answer: "Woman",
  },
  {
    id: 44,
    text: "The fear of vegetables is called ____.",
    answer: "Lachanophobia",
  },
  {
    id: 45,
    text: "In 2015, a man in Germany broke up with his girlfriend and sawed all their belongings in ____.",
    answer: "Half",
  },
  {
    id: 46,
    text: "The smell of rain hitting dry ground is called ____.",
    answer: "Petrichor",
  },
  {
    id: 47,
    text: "In 2017, a man in China tried to pay for a new car using only ____.",
    answer: "Coins",
  },
  {
    id: 48,
    text: "The little lump of flesh in front of your ear canal is called the ____.",
    answer: "Tragus",
  },
  { id: 49, text: "A group of crows is called a ____.", answer: "Murder" },
  {
    id: 50,
    text: "In 2010, a man in Korea married his ____.",
    answer: "Pillow",
  },
  {
    id: 51,
    text: "The fear of belly buttons is called ____.",
    answer: "Omphalophobia",
  },
  {
    id: 52,
    text: "In 2013, a man in Brazil was killed when a ____ fell through his roof.",
    answer: "Cow",
  },
  {
    id: 53,
    text: "The indentation between your nose and upper lip is called the ____.",
    answer: "Philtrum",
  },
  {
    id: 54,
    text: "In 2007, a man in Bosnia claimed he could stick ____ to his face.",
    answer: "Cans",
  },
  { id: 55, text: "A group of jellyfish is called a ____.", answer: "Smack" },
  {
    id: 56,
    text: "The fear of being without your mobile phone is called ____.",
    answer: "Nomophobia",
  },
  {
    id: 57,
    text: "In 2014, a man in the UK legally changed his name to ____.",
    answer: "Bacon Double Cheeseburger",
  },
  {
    id: 58,
    text: "The wire cage that holds the cork on a champagne bottle is called a ____.",
    answer: "Muselet",
  },
  {
    id: 59,
    text: "In 2011, a woman in the US was arrested for riding a ____ while intoxicated.",
    answer: "Horse",
  },
  { id: 60, text: "The fear of chins is called ____.", answer: "Geniophobia" },
  { id: 61, text: "Wombat poop is shaped like ____.", answer: "Cubes" },
  {
    id: 62,
    text: "Chainsaws were originally invented to help with ____.",
    answer: "Childbirth",
  },
  {
    id: 63,
    text: "Astronauts say the moon smells like ____.",
    answer: "Gunpowder",
  },
  {
    id: 64,
    text: "High heels were originally invented for ____.",
    answer: "Men",
  },
  { id: 65, text: "Cotton candy was invented by a ____.", answer: "Dentist" },
  {
    id: 66,
    text: "The technical name for the hashtag symbol (#) is ____.",
    answer: "Octothorpe",
  },
  { id: 67, text: "Barbie's middle name is ____.", answer: "Millicent" },
  {
    id: 68,
    text: "Trypophobia is the fear of clustered ____.",
    answer: "Holes",
  },
  {
    id: 69,
    text: "Sea otters hold ____ while sleeping to keep from drifting apart.",
    answer: "Hands",
  },
  {
    id: 70,
    text: "The inventor of the Frisbee was cremated and turned into a ____.",
    answer: "Frisbee",
  },
  { id: 71, text: "A group of rhinos is called a ____.", answer: "Crash" },
  {
    id: 72,
    text: "Originally, 3 Musketeers bars included chocolate, vanilla, and ____.",
    answer: "Strawberry",
  },
  {
    id: 73,
    text: "Hawaiian pizza was actually invented in ____.",
    answer: "Canada",
  },
  {
    id: 74,
    text: "The CIA once spent $20 million on a cat equipped with a ____.",
    answer: "Microphone",
  },
  {
    id: 75,
    text: "Bubble wrap was originally invented to be used as ____.",
    answer: "Wallpaper",
  },
  {
    id: 76,
    text: "Nintendo was founded in 1889 as a ____ company.",
    answer: "Playing Card",
  },
  {
    id: 77,
    text: "The Eiffel Tower grows about 6 inches in the ____.",
    answer: "Summer",
  },
  { id: 78, text: "A snail can sleep for ____ years.", answer: "Three" },
  {
    id: 79,
    text: "____ have fingerprints almost indistinguishable from humans.",
    answer: "Koalas",
  },
  {
    id: 80,
    text: "Botanically speaking, bananas are classified as ____.",
    answer: "Berries",
  },
  { id: 81, text: "A group of lemurs is called a ____.", answer: "Conspiracy" },
  {
    id: 82,
    text: "The King of England legally owns all the ____ in the River Thames.",
    answer: "Swans",
  },
  {
    id: 83,
    text: "Reno, Nevada is actually west of ____, California.",
    answer: "Los Angeles",
  },
  { id: 84, text: "The US state closest to Africa is ____.", answer: "Maine" },
  {
    id: 85,
    text: "Russia has a larger surface area than ____.",
    answer: "Pluto",
  },
  {
    id: 86,
    text: "Saudi Arabia imports camels from ____.",
    answer: "Australia",
  },
  { id: 87, text: "A baby puffin is called a ____.", answer: "Puffling" },
  {
    id: 88,
    text: "Talkeetna, Alaska elected a ____ as mayor for 20 years.",
    answer: "Cat",
  },
  {
    id: 89,
    text: "The Lyrebird is famous for mimicking the sound of ____.",
    answer: "Chainsaws",
  },
  {
    id: 90,
    text: "A group of pandas is called an ____.",
    answer: "Embarrassment",
  },
  {
    id: 91,
    text: "In 2009, Stephen Hawking threw a party for ____, but no one showed up.",
    answer: "Time Travelers",
  },
  {
    id: 92,
    text: "There are more ____ flamingos in the world than real ones.",
    answer: "Plastic",
  },
  {
    id: 93,
    text: "An average cumulus cloud weighs about 1.1 million ____.",
    answer: "Pounds",
  },
  {
    id: 94,
    text: "In 2015, a sheep named Chris was found with ____ pounds of wool.",
    answer: "90",
  },
  {
    id: 95,
    text: "The first mechanical alarm clock could only ring at ____.",
    answer: "4 AM",
  },
  { id: 96, text: "A group of frogs is called an ____.", answer: "Army" },
  {
    id: 97,
    text: "In 2014, an exchange student in Germany got stuck inside a giant stone statue of a ____.",
    answer: "Vagina",
  },
  { id: 98, text: "A group of stingrays is called a ____.", answer: "Fever" },
  {
    id: 99,
    text: "In 2011, a monkey was arrested in Pakistan for crossing the ____.",
    answer: "Border",
  },
  { id: 100, text: "A group of zebras is called a ____.", answer: "Dazzle" },
  {
    id: 101,
    text: "In 2015, a man sued himself for hitting himself with a ____.",
    answer: "Boomerang",
  },
  {
    id: 102,
    text: "A group of rattlesnakes is called a ____.",
    answer: "Rhumba",
  },
  { id: 103, text: "Turophobia is the fear of ____.", answer: "Cheese" },
  {
    id: 104,
    text: "Nomophobia is the fear of being without your ____.",
    answer: "Mobile Phone",
  },
  {
    id: 105,
    text: "In 2014, a man in the UK legally changed his name to ____.",
    answer: "Bacon Double Cheeseburger",
  },
  {
    id: 106,
    text: "The wire cage that holds the cork on a champagne bottle is called a ____.",
    answer: "Muselet",
  },
  { id: 107, text: "Pogonophobia is the fear of ____.", answer: "Beards" },
  {
    id: 108,
    text: "Omphalophobia is the fear of ____.",
    answer: "Belly Buttons",
  },
  {
    id: 109,
    text: "Oxford University is older than the ____ Empire.",
    answer: "Aztec",
  },
  {
    id: 110,
    text: "____ can hold their breath longer than dolphins.",
    answer: "Sloths",
  },
  { id: 111, text: "A group of owls is called a ____.", answer: "Parliament" },
  {
    id: 112,
    text: "In 1923, a jockey named Frank Hayes won a race despite being ____.",
    answer: "Dead",
  },
  {
    id: 113,
    text: "The plastic tip at the end of a shoelace is called an ____.",
    answer: "Aglet",
  },
  {
    id: 114,
    text: "The fear of being tickled by feathers is called ____.",
    answer: "Pteronophobia",
  },
  { id: 115, text: "A baby porcupine is called a ____.", answer: "Porcupette" },
  {
    id: 116,
    text: "In the 18th century, wealthy British garden owners would hire people to be ornamental ____.",
    answer: "Hermits",
  },
  {
    id: 117,
    text: "The dot over the letter 'j' is called a ____.",
    answer: "Tittle",
  },
  { id: 118, text: "A group of crows is called a ____.", answer: "Murder" },
  {
    id: 119,
    text: "The space between your eyebrows is called the ____.",
    answer: "Glabella",
  },
  {
    id: 120,
    text: "In 2007, a woman in the US married the ____.",
    answer: "Eiffel Tower",
  },
  {
    id: 121,
    text: "The fear of long words is ironically called ____.",
    answer: "Hippopotomonstrosesquippedaliophobia",
  },
  {
    id: 122,
    text: "A single strand of spaghetti is called a ____.",
    answer: "Spaghetto",
  },
  {
    id: 123,
    text: "The tiny pocket in jeans was originally designed to hold ____.",
    answer: "Watches",
  },
  {
    id: 124,
    text: "The smell of rain hitting dry soil is called ____.",
    answer: "Petrichor",
  },
  { id: 125, text: "A group of ferrets is called a ____.", answer: "Business" },
  {
    id: 126,
    text: "The indentation between your nose and upper lip is called the ____.",
    answer: "Philtrum",
  },
  {
    id: 127,
    text: "In 1386, a pig in France was executed by public hanging for the murder of a ____.",
    answer: "Child",
  },
  {
    id: 128,
    text: "The fear of buttons is called ____.",
    answer: "Koumpounophobia",
  },
  { id: 129, text: "A group of jellyfish is called a ____.", answer: "Smack" },
  {
    id: 130,
    text: "The metal band that holds a pencil eraser in place is called a ____.",
    answer: "Ferrule",
  },
  {
    id: 131,
    text: "In 2012, a man in Sweden was arrested for trying to split atoms in his ____.",
    answer: "Kitchen",
  },
  {
    id: 132,
    text: "The fear of cooking is called ____.",
    answer: "Mageirocophobia",
  },
  { id: 133, text: "A group of stingrays is called a ____.", answer: "Fever" },
  {
    id: 134,
    text: "The cardboard sleeve on a coffee cup is called a ____.",
    answer: "Zarf",
  },
  {
    id: 135,
    text: "In 2016, a man in Florida threw a ____ through a drive-thru window.",
    answer: "Alligator",
  },
  {
    id: 136,
    text: "The fear of palindromes is called ____.",
    answer: "Aibohphobia",
  },
  { id: 137, text: "A group of hippos is called a ____.", answer: "Bloat" },
  {
    id: 138,
    text: "The symbol used for division (÷) is technically called an ____.",
    answer: "Obelus",
  },
  {
    id: 139,
    text: "In 2011, a woman bought a piece of 'invisible art' for $10,000 made entirely of ____.",
    answer: "Air",
  },
  { id: 140, text: "The fear of knees is called ____.", answer: "Genuphobia" },
  {
    id: 141,
    text: "A group of ravens is called an ____.",
    answer: "Unkindness",
  },
  {
    id: 142,
    text: "The infinity symbol (∞) is technically called a ____.",
    answer: "Lemniscate",
  },
  {
    id: 143,
    text: "In 2008, a man in Zimbabwe was arrested for 'criminal nuisance' after he was caught ____ at a police car.",
    answer: "Laughing",
  },
  {
    id: 144,
    text: "The fear of the color yellow is called ____.",
    answer: "Xanthophobia",
  },
  { id: 145, text: "A group of zebras is called a ____.", answer: "Dazzle" },
  {
    id: 146,
    text: "The white, crescent-shaped area at the base of a fingernail is called the ____.",
    answer: "Lunule",
  },
  {
    id: 147,
    text: "In 2015, a man in Germany sawed all his belongings in ____ after a breakup.",
    answer: "Half",
  },
  { id: 148, text: "The fear of flutes is called ____.", answer: "Aulophobia" },
  { id: 149, text: "A group of frogs is called an ____.", answer: "Army" },
  {
    id: 150,
    text: "The little lump of flesh in front of your ear canal is called the ____.",
    answer: "Tragus",
  },
  {
    id: 151,
    text: "In 2013, a pig in Australia stole 18 beers and got into a fight with a ____.",
    answer: "Cow",
  },
  {
    id: 152,
    text: "The fear of vegetables is called ____.",
    answer: "Lachanophobia",
  },
  {
    id: 153,
    text: "A group of lemurs is called a ____.",
    answer: "Conspiracy",
  },
  {
    id: 154,
    text: "The day after tomorrow is technically called ____.",
    answer: "Overmorrow",
  },
  {
    id: 155,
    text: "In 2014, a woman was arrested in Pennsylvania for shoplifting 50 bottles of ____.",
    answer: "Air Freshener",
  },
  { id: 156, text: "The fear of chins is called ____.", answer: "Geniophobia" },
  { id: 157, text: "A group of wombats is called a ____.", answer: "Wisdom" },
  {
    id: 158,
    text: "The rumble your stomach makes when you are hungry is called ____.",
    answer: "Borborygmus",
  },
  {
    id: 159,
    text: "In 2009, Stephen Hawking threw a party for ____, but no one showed up.",
    answer: "Time Travelers",
  },
  {
    id: 160,
    text: "The fear of beautiful women is called ____.",
    answer: "Venustraphobia",
  },
  {
    id: 161,
    text: "Cap'n Crunch's full name is ____ Magellan Crunch.",
    answer: "Horatio",
  },
  { id: 162, text: "The Cookie Monster's real name is ____.", answer: "Sid" },
  {
    id: 163,
    text: "The Michelin Man's actual name is ____.",
    answer: "Bibendum",
  },
  { id: 164, text: "Hippo milk is naturally ____.", answer: "Pink" },
  { id: 165, text: "Slugs have four ____.", answer: "Noses" },
  { id: 166, text: "An octopus has three ____.", answer: "Hearts" },
  { id: 167, text: "A baby echidna is called a ____.", answer: "Puggle" },
  { id: 168, text: "Platypuses have no ____.", answer: "Stomachs" },
  { id: 169, text: "A shrimp's heart is located in its ____.", answer: "Head" },
  {
    id: 170,
    text: "Kangaroo rats can go their entire lives without drinking ____.",
    answer: "Water",
  },
  {
    id: 171,
    text: "The Turritopsis dohrnii is a species of jellyfish that is biologically ____.",
    answer: "Immortal",
  },
  {
    id: 172,
    text: "A blue whale's heart is the size of a ____.",
    answer: "Car",
  },
  {
    id: 173,
    text: "An ostrich's eye is bigger than its ____.",
    answer: "Brain",
  },
  {
    id: 174,
    text: "Underneath their fur, polar bears have ____ skin.",
    answer: "Black",
  },
  {
    id: 175,
    text: "Cows can walk up stairs, but they cannot walk ____.",
    answer: "Down",
  },
  {
    id: 176,
    text: "It is physically impossible for pigs to look up at the ____.",
    answer: "Sky",
  },
  { id: 177, text: "Butterflies taste with their ____.", answer: "Feet" },
  {
    id: 178,
    text: "Elephants are the only mammal that cannot ____.",
    answer: "Jump",
  },
  {
    id: 179,
    text: "When exiting a cave, bats always turn ____.",
    answer: "Left",
  },
  { id: 180, text: "A crocodile cannot stick out its ____.", answer: "Tongue" },
  { id: 181, text: "Starfish have no ____.", answer: "Brain" },
  {
    id: 182,
    text: "Honey is the only food that never ____.",
    answer: "Spoils",
  },
  { id: 183, text: "Peanuts are not nuts, they are ____.", answer: "Legumes" },
  {
    id: 184,
    text: "Almonds are a member of the ____ family.",
    answer: "Peach",
  },
  { id: 185, text: "Apples float because they are 25% ____.", answer: "Air" },
  {
    id: 186,
    text: "Ripe cranberries will ____ if you drop them.",
    answer: "Bounce",
  },
  {
    id: 187,
    text: "Genetically, mushrooms are more closely related to ____ than plants.",
    answer: "Humans",
  },
  {
    id: 188,
    text: "Corn always grows in an ____ number of rows.",
    answer: "Even",
  },
  { id: 189, text: "Originally, carrots were ____.", answer: "Purple" },
  {
    id: 190,
    text: "Artificial vanilla flavoring (Castoreum) comes from a gland in a beaver's ____.",
    answer: "Butt",
  },
  {
    id: 191,
    text: "The red food dye 'Carmine' is made from crushed ____.",
    answer: "Beetles",
  },
  {
    id: 192,
    text: "The shiny coating on jelly beans (Shellac) is made from ____ poop.",
    answer: "Bug",
  },
  {
    id: 193,
    text: "France's longest border is shared with ____.",
    answer: "Brazil",
  },
  {
    id: 194,
    text: "Canada has more ____ than the rest of the world combined.",
    answer: "Lakes",
  },
  { id: 195, text: "China has only one ____.", answer: "Time Zone" },
  {
    id: 196,
    text: "The official birth rate of Vatican City is ____.",
    answer: "Zero",
  },
  { id: 197, text: "Napoleon was actually of ____ height.", answer: "Average" },
  {
    id: 198,
    text: "Vikings never actually wore horned ____.",
    answer: "Helmets",
  },
  {
    id: 199,
    text: "Cleopatra lived closer in time to the ____ than the Pyramids.",
    answer: "iPhone",
  },
  {
    id: 200,
    text: "The T-Rex lived closer in time to ____ than to the Stegosaurus.",
    answer: "Humans",
  },
  {
    id: 201,
    text: "Woolly Mammoths were still alive when the ____ were being built.",
    answer: "Pyramids",
  },
  {
    id: 202,
    text: "Tiffany & Co. is older than the country of ____.",
    answer: "Italy",
  },
  { id: 203, text: "Betty White was older than sliced ____.", answer: "Bread" },
  {
    id: 204,
    text: "Harvard University was founded before ____ was invented.",
    answer: "Calculus",
  },
  { id: 205, text: "Sharks have existed longer than ____.", answer: "Trees" },
  {
    id: 206,
    text: "The lighter was invented before the ____.",
    answer: "Match",
  },
  {
    id: 207,
    text: "The medical term for a 'brain freeze' is ____ ganglioneuralgia.",
    answer: "Sphenopalatine",
  },
  {
    id: 208,
    text: "The medical term for the struggle to get out of bed in the morning is ____.",
    answer: "Dysania",
  },
  {
    id: 209,
    text: "The act of throwing someone out of a window is called ____.",
    answer: "Defenestration",
  },
  {
    id: 210,
    text: "The 'flesh' of a strawberry is actually swollen ____ tissue.",
    answer: "Ovary",
  },
  {
    id: 211,
    text: "Anatidaephobia is the irrational fear that somewhere, somehow, a ____ is watching you.",
    answer: "Duck",
  },
  {
    id: 212,
    text: "In 1999, the founders of Google tried to sell the company for $1 million to ____.",
    answer: "Excite",
  },
  {
    id: 213,
    text: "Play-Doh was originally invented to clean ____.",
    answer: "Wallpaper",
  },
  {
    id: 214,
    text: "The offspring of a cow and a bison is called a ____.",
    answer: "Beefalo",
  },
  {
    id: 215,
    text: "The dots on a domino or dice are technically called ____.",
    answer: "Pips",
  },
  {
    id: 216,
    text: "Triskaidekaphobia is the fear of the number ____.",
    answer: "13",
  },
  {
    id: 217,
    text: "In 1986, Apple released a clothing line called 'The Apple ____'.",
    answer: "Collection",
  },
  {
    id: 218,
    text: "The first item ever scanned with a UPC barcode was a pack of ____.",
    answer: "Gum",
  },
  { id: 219, text: "A group of squirrels is called a ____.", answer: "Scurry" },
  {
    id: 220,
    text: "The symbol '&' was once considered the 27th letter of the alphabet and is called an ____.",
    answer: "Ampersand",
  },
  { id: 221, text: "Ergophobia is the fear of ____.", answer: "Work" },
  { id: 222, text: "Chrometophobia is the fear of ____.", answer: "Money" },
  {
    id: 223,
    text: "In 2013, a man bought a house next to his ex-wife just to install a giant statue of a ____.",
    answer: "Middle Finger",
  },
  {
    id: 224,
    text: "The voice actor for Mickey Mouse was married to the voice actor for ____.",
    answer: "Minnie Mouse",
  },
  {
    id: 225,
    text: "In 2006, a woman lit matches on a flight to cover the smell of her ____.",
    answer: "Farts",
  },
  {
    id: 226,
    text: "The official state vegetable of Oklahoma is the ____.",
    answer: "Watermelon",
  },
  {
    id: 227,
    text: "In 1998, the U.S. Navy used Xbox controllers to operate ____.",
    answer: "Periscopes",
  },
  {
    id: 228,
    text: "The first YouTube video ever uploaded was titled 'Me at the ____'.",
    answer: "Zoo",
  },
  {
    id: 229,
    text: "The original name for the search engine Google was ____.",
    answer: "BackRub",
  },
  {
    id: 230,
    text: "The mascot of Pringles is named ____ Pringles.",
    answer: "Julius",
  },
  {
    id: 231,
    text: "The mascot of Monopoly is named Rich Uncle ____.",
    answer: "Pennybags",
  },
  {
    id: 232,
    text: "The ridges on the edge of a coin are called ____.",
    answer: "Reeding",
  },
  {
    id: 233,
    text: "The medical term for feeling sick from eating or drinking too much is ____.",
    answer: "Crapulence",
  },
  {
    id: 234,
    text: "Vestiphobia is the irrational fear of ____.",
    answer: "Clothing",
  },
  { id: 235, text: "Dendrophobia is the fear of ____.", answer: "Trees" },
  { id: 236, text: "Barophobia is the fear of ____.", answer: "Gravity" },
  {
    id: 237,
    text: "In 2015, a Florida man called 911 because his ____ was too small.",
    answer: "Clam",
  },
  {
    id: 238,
    text: "A man in Japan married a hologram of ____.",
    answer: "Hatsune Miku",
  },
  {
    id: 239,
    text: "In 2007, a man in India married a ____ to ward off a curse.",
    answer: "Dog",
  },
  {
    id: 240,
    text: "The first food eaten in space was ____.",
    answer: "Applesauce",
  },
  {
    id: 241,
    text: "Astronauts cannot ____ in space because there is no gravity to pull tears down.",
    answer: "Cry",
  },
  {
    id: 242,
    text: "The moon is moving away from Earth at the same speed that ____ grow.",
    answer: "Fingernails",
  },
  {
    id: 243,
    text: "A day on Venus is longer than a ____ on Venus.",
    answer: "Year",
  },
  { id: 244, text: "Sunset on Mars appears ____.", answer: "Blue" },
  {
    id: 245,
    text: "The national animal of Canada is the ____.",
    answer: "Beaver",
  },
  {
    id: 246,
    text: "Ben Franklin wanted the national bird of the US to be the ____.",
    answer: "Turkey",
  },
  { id: 247, text: "A baby spider is called a ____.", answer: "Spiderling" },
  { id: 248, text: "A baby fish is called a ____.", answer: "Fry" },
  {
    id: 249,
    text: "A group of kittens is technically called a ____.",
    answer: "Kindle",
  },
  { id: 250, text: "A group of giraffes is called a ____.", answer: "Tower" },
  { id: 251, text: "A group of sharks is called a ____.", answer: "Shiver" },
  {
    id: 252,
    text: "The indentation at the bottom of a wine bottle is called a ____.",
    answer: "Punt",
  },
  {
    id: 253,
    text: "Humans share about 50% of their DNA with ____.",
    answer: "Bananas",
  },
  {
    id: 254,
    text: "A group of rabbits is affectionately known as a ____.",
    answer: "Fluffle",
  },
  {
    id: 255,
    text: "Kleenex tissues were originally invented for use in ____.",
    answer: "Gas Masks",
  },
  {
    id: 256,
    text: "Viagra was originally developed to treat ____.",
    answer: "Heart Angina",
  },
  {
    id: 257,
    text: "The longest word in the English language with only one vowel is ____.",
    answer: "Strengths",
  },
  {
    id: 258,
    text: "Barry Manilow wrote the famous jingle 'Like a good neighbor, ____ is there.'",
    answer: "State Farm",
  },
  {
    id: 259,
    text: "About 3% of the ice in Antarctic glaciers is made of ____.",
    answer: "Penguin Urine",
  },
  {
    id: 260,
    text: "In physics, a 'jiffy' is an actual unit of ____.",
    answer: "Time",
  },
  {
    id: 261,
    text: "In 2013, Dell issued a recall after customers complained their laptops smelled like ____.",
    answer: "Cat Urine",
  },
  {
    id: 262,
    text: "According to a University of Jena study, the people who have the most memorable faces are ____ people.",
    answer: "Ugly",
  },
  {
    id: 263,
    text: "In October of 2013, eight sixth-graders from a New York college prep school were hospitalized after someone released ____ in a classroom.",
    answer: "Axe Body Spray",
  },
  {
    id: 264,
    text: "When in Port Vila, Vanuatu be sure to check out their post office, which is unusual because it is ____.",
    answer: "Underwater",
  },
  {
    id: 265,
    text: "The Kila Raipur Sports Festival, held annually in Punjab, India, has an event where participants lay on the ground and get ____.",
    answer: "Run Over By A Tractor",
  },
  {
    id: 266,
    text: "After an allergic reaction to steroids used to treat asthma, a 28-year-old woman started growing ____ on her head instead of hair.",
    answer: "Fingernails",
  },
  {
    id: 267,
    text: "In a 1999 interview with US Weekly, actress Lucy Liu revealed that she once had sex with a ____.",
    answer: "Ghost",
  },
  {
    id: 268,
    text: "The city of Olney, Illinois organizes an annual event in order to ____ squirrels.",
    answer: "Count",
  },
  {
    id: 269,
    text: "While in Florence, New Jersey be sure to check out the auto repair shop which has an operational toilet once owned by ____.",
    answer: "Hitler",
  },
  {
    id: 270,
    text: "A Kickstarter campaign met its $30,000 goal on April 7, 2012 for its shoes designed for ____.",
    answer: "Atheists",
  },
  {
    id: 271,
    text: "Kevin Spacey’s older brother is a ____ impersonator.",
    answer: "Rod Stewart",
  },
  {
    id: 272,
    text: "Andrew Wilson, a man from Branson, Missouri, legally changed his name to simply ____.",
    answer: "They",
  },
  {
    id: 273,
    text: "Under Peter the Great, noblemen had to pay 100 rubles a year for a ____ license.",
    answer: "Beard",
  },
  {
    id: 274,
    text: "In 2008, a couple was killed in South Africa while having sex on a ____.",
    answer: "Railroad Track",
  },
  {
    id: 275,
    text: "In the 16th century, gin was referred to as Mother’s ____.",
    answer: "Ruin",
  },
  {
    id: 276,
    text: "Amerigo Vespucci, the man for whom America was named, was a ____ dealer.",
    answer: "Pickle",
  },
  {
    id: 277,
    text: "Walter Arnold received the world’s first speeding ticket in 1896 for going ____ miles per hour.",
    answer: "8",
  },
  {
    id: 278,
    text: "Edgar Valdez Villarreal, a notorious Mexican drug cartel leader, had the not-so-scary nickname “La ____.”",
    answer: "Barbie",
  },
  {
    id: 279,
    text: "Frank Hayes is the first jockey to win a race while ____.",
    answer: "Dead",
  },
  {
    id: 280,
    text: "Tashirojima is an island off of Japan that is completely overrun by ____.",
    answer: "Cats",
  },
  {
    id: 281,
    text: "The Isle of Man flag depicts three ____ interlinked together.",
    answer: "Legs",
  },
  {
    id: 282,
    text: "Shiro Cosmetics sells an eye shadow called “____ Raking Leaves on a Brisk October Afternoon.”",
    answer: "Nic Cage",
  },
  {
    id: 283,
    text: "Maryland’s official state sport is ____.",
    answer: "Jousting",
  },
  {
    id: 284,
    text: "In 1967, a small town in Ecuador elected an inanimate object mayor. The elected mayor was a ____.",
    answer: "Foot Powder",
  },
  {
    id: 285,
    text: "A group known as the “Robin Hooders” in Keene, New Hampshire pay for other people’s ____.",
    answer: "Parking Meters",
  },
  {
    id: 286,
    text: "As a way to protest Belarus’ police state, a Swedish group dropped hundreds of ____ from an airplane.",
    answer: "Teddy Bears",
  },
  {
    id: 287,
    text: "A man in western Pennsylvania got a DUI for having an open can of beer while riding a ____.",
    answer: "Lawn Mower",
  },
  {
    id: 288,
    text: "Anatidaephobia is the fear that somewhere in the world a ____ is watching you.",
    answer: "Duck",
  },
  {
    id: 289,
    text: "For his voiceover work in Texas Chainsaw Massacre, John Larroquette was paid not with money, but with ____.",
    answer: "Marijuana",
  },
  {
    id: 290,
    text: "Famed American poet Charles Bukowski’s tombstone is engraved with the words “Don’t ____.”",
    answer: "Try",
  },
  {
    id: 291,
    text: "Huggies Brazil developed a phone app that tells you when a baby’s diaper is wet. It’s called ____.",
    answer: "TweetPee",
  },
  {
    id: 292,
    text: "A beaver’s anal secretions can be used as a ____ substitute in some foods.",
    answer: "Vanilla",
  },
  {
    id: 293,
    text: "A spectator in an Illinois courtroom was sentenced to six months in jail for ____ during a trial.",
    answer: "Yawning",
  },
  {
    id: 294,
    text: "The German Primate Center conducted a study called “Why Female Monkeys ____ During Sex.”",
    answer: "Shout",
  },
  {
    id: 295,
    text: "According to a Logitech study, 49% of lost remote controls are found in the couch, while 4% are found in the ____.",
    answer: "Fridge",
  },
  {
    id: 296,
    text: "In 2010, Customs officers on the Norway-Sweden border intercepted a truck trying to smuggle 28 tons of ____ from China.",
    answer: "Garlic",
  },
  {
    id: 297,
    text: "The French have a pastry called “Nun’s ____.”",
    answer: "Fart",
  },
  {
    id: 298,
    text: "Alexander the Great made his men ____ before a battle.",
    answer: "Shave",
  },
  {
    id: 299,
    text: "Monroe Isadore, a 107-year-old man from Arkansas, died during a ____.",
    answer: "Shootout",
  },
  {
    id: 300,
    text: "At the Meitestu-Nagoya train station in Japan, there’s an odd vending machine that sells ____.",
    answer: "Porn",
  },
  {
    id: 301,
    text: "A sequel to Beetlejuice titled Beetlejuice Goes ____ was written but never made.",
    answer: "Hawaiian",
  },
  {
    id: 302,
    text: "An eight-foot-tall ____ washed up ashore a Florida beach in 2011.",
    answer: "Lego Man",
  },
  {
    id: 303,
    text: "Freddie Mercury backed out of a duet with Michael Jackson because Jackson brought a ____ to the recording studio.",
    answer: "Llama",
  },
  {
    id: 304,
    text: "People in Damariscotta, Maine hold an annual race where they use ____ as boats.",
    answer: "Pumpkins",
  },
  {
    id: 305,
    text: "An Indiana woman sued a church cemetery because they refused to install her late husband’s tombstone shaped like a ____.",
    answer: "Couch",
  },
  {
    id: 306,
    text: "Jacobite Cruises purchased unusual insurance to protect it from damage caused by ____.",
    answer: "The Loch Ness Monster",
  },
  {
    id: 307,
    text: "Forest Whitaker has three daughters (Sonnet, True and Autumn) and a son named ____.",
    answer: "Ocean",
  },
  {
    id: 308,
    text: "While in Alliance, Nebraska, you can visit the Stonehenge replica made out of ____.",
    answer: "Cars",
  },
  {
    id: 309,
    text: "A woman in Muncie, Indiana was hospitalized after trying to remove a callus on her foot with a ____.",
    answer: "Shotgun",
  },
  {
    id: 310,
    text: "A Florida man choked to death on cockroaches he ate while trying to win a ____.",
    answer: "Python",
  },
  {
    id: 311,
    text: "At the Sao Joao festival in Portugal, you hit people over the head with a ____.",
    answer: "Hammer",
  },
  {
    id: 312,
    text: "In a 2012 poll, Denzel Washington was voted the public’s first choice to play the character of ____.",
    answer: "Jesus",
  },
  {
    id: 313,
    text: "William Shatner raised $25,000 for Habitat for Humanity by selling his ____.",
    answer: "Kidney Stone",
  },
  {
    id: 314,
    text: "For one day in 1998, Topeka, Kansas renamed itself ____.",
    answer: "ToPikachu",
  },
  {
    id: 315,
    text: "There was once a fourth member of Kellogg’s Rice Krispies mascot gang. Originally it was Snap, Crackle, Pop and ____.",
    answer: "Pow",
  },
  {
    id: 316,
    text: "In 2006, the wax museum Madame Tussaud’s in New York City introduced its first wax ____.",
    answer: "Baby",
  },
  {
    id: 317,
    text: "In 2007, a woman with a rare disorder that causes her to be sexually attracted to inanimate objects married ____.",
    answer: "The Eiffel Tower",
  },
  {
    id: 318,
    text: "On his own website, magician David Blaine once wrote, “The most courageous act a man can do is ____.”",
    answer: "Cry",
  },
  {
    id: 319,
    text: "The fans of musician Josh Groban are called ____.",
    answer: "Grobanites",
  },
  {
    id: 320,
    text: "The sound of E.T. walking was made by someone squishing ____.",
    answer: "Jell-O",
  },
  {
    id: 321,
    text: "In 1980, Saddam Hussein was named an honorary citizen of ____.",
    answer: "Detroit",
  },
  {
    id: 322,
    text: "Britt, Iowa annually crowns a King and Queen ____.",
    answer: "Hobo",
  },
  {
    id: 323,
    text: "The University of Victoria offers a physical education class called The Science of ____.",
    answer: "Batman",
  },
  {
    id: 324,
    text: "A 2013 Pakistani game show caused a controversy when their grand prize was a ____.",
    answer: "Baby",
  },
  {
    id: 325,
    text: "The Lehigh Valley IronPigs, a minor league baseball team, held a contest where the prize was a voucher for a ____.",
    answer: "Funeral",
  },
  {
    id: 326,
    text: "Every year residents in Ivrea, Italy reenact a historical battle of their region, and instead of replica weapons, they use ____.",
    answer: "Oranges",
  },
  { id: 327, text: "The mayor of Rabbit Hash, KY is a ____.", answer: "Dog" },
  {
    id: 328,
    text: "Nigeria’s version of Cookie Monster can’t stop eating ____.",
    answer: "Yams",
  },
  {
    id: 329,
    text: "While president of the United States, John Adams had a dog named Juno and a dog named ____.",
    answer: "Satan",
  },
  {
    id: 330,
    text: "Tara Reid once said, “I make Jessica Simpson look like a ____ scientist.”",
    answer: "Rock",
  },
  {
    id: 331,
    text: "Advanced Comfort Technology makes waterbeds for ____.",
    answer: "Cows",
  },
  {
    id: 332,
    text: "Mexico’s Isla de las Munecas is an attraction known for having hundreds of ____ hanging in its trees.",
    answer: "Dolls",
  },
  {
    id: 333,
    text: "El Colacho is a Spanish festival where people dress up like the devil and jump over ____.",
    answer: "Babies",
  },
  {
    id: 334,
    text: "In 2013, a U.S. Customs and Border Protection Officer was found guilty of granting citizenship in exchange for 200 ____.",
    answer: "Egg Rolls",
  },
  {
    id: 335,
    text: "A man in L.A. was arrested at a police-sponsored gun buyback when, instead of a gun, he tried to sell the cops a ____.",
    answer: "Pipe Bomb",
  },
  {
    id: 336,
    text: "Utah’s Lehi City Council approved a request to change the name of ____ Road because it sounded sort of dirty.",
    answer: "Morning Glory",
  },
  {
    id: 337,
    text: "It’s weird work but Jackie Samuel charges $60 an hour to ____.",
    answer: "Snuggle",
  },
  {
    id: 338,
    text: "A British woman was arrested for hijacking a British ferry and yelling, “____!”",
    answer: "I’m Jack Sparrow",
  },
  {
    id: 339,
    text: "In 2013, the Rethink ad agency placed red beer fridges throughout Europe that could only be opened by ____.",
    answer: "Canadians",
  },
  {
    id: 340,
    text: "The movie G.I. Jane was translated to ____ Female Soldier in China.",
    answer: "Satan",
  },
  {
    id: 341,
    text: "According to Forbes, the average income for an “ice cream taster” is $____ a year.",
    answer: "56,000",
  },
  {
    id: 342,
    text: "During a famous fire in 1567, a Norwegian man named Hans Steininger died after tripping over a ____.",
    answer: "Beard",
  },
  {
    id: 343,
    text: "The inventor of the laxative Ex-Lax has the unusual name Max ____.",
    answer: "Kiss",
  },
  {
    id: 344,
    text: "To make it extremely difficult for telemarketers to pronounce, Tim Price changed his name in 2012 to Tim ____.",
    answer: "Ppppppppppprice",
  },
  {
    id: 345,
    text: "In 1976, boxing legend Muhammad Ali released an educational children’s album titled “Ali and His Gang Vs. Mr. ____.”",
    answer: "Tooth Decay",
  },
  {
    id: 346,
    text: "The area in the Pacific Ocean where great white sharks congregate every spring is called the White Shark ____.",
    answer: "Cafe",
  },
  {
    id: 347,
    text: "As a way to relieve stress for its students, Dalhousie University in 2012 introduced a ____ Room.",
    answer: "Puppy",
  },
  {
    id: 348,
    text: "In 2013, two teens from Sequoyah High School near Atlanta, Georgia won $5,000 scholarships for wearing ____ to prom.",
    answer: "Duct Tape",
  },
  {
    id: 349,
    text: "Loyola University offers a scholarship to any Catholic students with the last name ____.",
    answer: "Zolp",
  },
  {
    id: 350,
    text: "Edward Smith from Yelm, Washington garnered media attention for his claim that he’s had sex with over 1,000 ____.",
    answer: "Cars",
  },
  {
    id: 351,
    text: "Cheap Chic Weddings is an annual contest in which participants make wedding dresses out of ____.",
    answer: "Toilet Paper",
  },
  {
    id: 352,
    text: "At 2:45 a.m. one day in June 2013, a man in Orlando, Florida was arrested for walking up to a police officer and punching his ____.",
    answer: "Horse",
  },
  {
    id: 353,
    text: "Located near the town of Stanley, there’s a small village in England called No ____.",
    answer: "Place",
  },
  {
    id: 354,
    text: "Jim Begelow, Ph.D., wrote a book called The Joy of Un____!.",
    answer: "Circumcising",
  },
  {
    id: 355,
    text: "In 2007, to make a point, Nebraska State Sen. Ernie Chambers filed a frivolous lawsuit against ____.",
    answer: "God",
  },
  {
    id: 356,
    text: "For $180, the Shizuka New York skin care salon offers an unusual but traditional Japanese facial that is part rice bran and part ____.",
    answer: "Bird Poop",
  },
  {
    id: 357,
    text: "Edwin E. Holmes, a man with very specific interests, wrote the 254-page book “A History of ____.”",
    answer: "Thimbles",
  },
  {
    id: 358,
    text: "Barbara E. Mattick wrote the book, A Guide to Bone ____ of the 19th and Early 20th Centuries.",
    answer: "Toothbrushes",
  },
  {
    id: 359,
    text: "Haribo sells a gummi in Germany that depicts a human butt with ____ growing out of it.",
    answer: "Ears",
  },
  {
    id: 360,
    text: "Suffering from an extremely rare side effect after getting hip surgery in 2010, a Dutch man has alienated his family because he cannot stop ____.",
    answer: "Laughing",
  },
  {
    id: 361,
    text: "Leo Granit Kraft is a world champion in an unusual sport that combines boxing and ____.",
    answer: "Chess",
  },
  {
    id: 362,
    text: "Only about 14 games were ever made for the Gizmondo game system, including the game “____ Balls.”",
    answer: "Sticky",
  },
  {
    id: 363,
    text: "The Nintendo DS had a dictionary program with the unfortunate name “____ Dic.”",
    answer: "Touch",
  },
  {
    id: 364,
    text: "Blake Shelton tweeted, “Just fell down and gashed my hand open while running from ____... Don’t ask.”",
    answer: "An Ostrich",
  },
  {
    id: 365,
    text: "The Chinese plant “pyschotria elata” is also known as “____ Lips.”",
    answer: "Hooker’s",
  },
  {
    id: 366,
    text: "During the summer of 2007, Pepsi sold a green-tinted cola in Japan called Pepsi Ice ____.",
    answer: "Cucumber",
  },
  {
    id: 367,
    text: "Over the course of 35 years, artist Scott Weaver has built a replica of the city of San Francisco using over 100,000 ____.",
    answer: "Toothpicks",
  },
  {
    id: 368,
    text: "While in Washington state go see the unusually named ____ Dick Mountain.",
    answer: "Whiskey",
  },
  {
    id: 369,
    text: "On October 24th, 2013 a man in Columbus, Georgia ran into his burning home in order to save his ____.",
    answer: "Beer",
  },
  {
    id: 370,
    text: "A chemistry teacher in Indiana was fired in 2013 after he allegedly took several of his students on an unauthorized field trip to a ____.",
    answer: "Strip Club",
  },
  {
    id: 371,
    text: "Unagi Travel is an unusual Japanese travel agency that sends your ____ on vacations.",
    answer: "Stuffed Animals",
  },
  {
    id: 372,
    text: "Scottsdale Community College’s sports teams are oddly named the Fighting ____.",
    answer: "Artichokes",
  },
  {
    id: 373,
    text: "A neurology professor at Albany Medical College documented in a 1991 medical journal that one of his patients had seizures when she heard ____.",
    answer: "Mary Hart’s Voice",
  },
  {
    id: 374,
    text: "Since 2000, a couple in Queens, New York has been living rent-free in a ____ in exchange for taking care of it.",
    answer: "Cemetery",
  },
  {
    id: 375,
    text: "A man in Wales, UK, is so obsessed with baked beans that in 1991 he legally changed his name to ____.",
    answer: "Captain Beany",
  },
  {
    id: 376,
    text: "In 1979, Clairol introduced and then almost immediately discontinued the oddly named “Touch of ____” shampoo.",
    answer: "Yogurt",
  },
  {
    id: 377,
    text: "Because he found Chinese food to be odd, during the 2008 Beijing Olympics, sprinter Usain Bolt said that he ended up eating 1,000 ____.",
    answer: "McNuggets",
  },
  {
    id: 378,
    text: "In an effort to push “slow TV,” Norway had a 12-hour block of programming in 2013 dedicated to ____.",
    answer: "Knitting",
  },
  {
    id: 379,
    text: "With 88 catches, Canadian Aaron Gregg holds the Guinness World Record for ____ juggling.",
    answer: "Chainsaw",
  },
  {
    id: 380,
    text: "Sponsored by the Calvary Lutheran Church, people in Fort Worth Texas can now attend the unconventional Church-in-a-____.",
    answer: "Pub",
  },
  {
    id: 381,
    text: "Due to its unusual mating habits, the New Mexico whiptail is nicknamed the ____ lizard.",
    answer: "Lesbian",
  },
  {
    id: 382,
    text: "Belmont University in Nashville has offered a class called “Oh, Look, a ____.”",
    answer: "Chicken",
  },
  {
    id: 383,
    text: "Although very unconventional, farmer William von Schneidau feeds his pigs ____.",
    answer: "Marijuana",
  },
  {
    id: 384,
    text: "Ben and Jerry only started making ice cream because it was too expensive to make ____.",
    answer: "Bagels",
  },
  {
    id: 385,
    text: "In 1977, Simulations Publications, Inc. published a strangely named board game called After The ____.",
    answer: "Holocaust",
  },
  {
    id: 386,
    text: "In 2007, Golden Laurel Entertainment published a violent board game called Kill the ____.",
    answer: "Hippies",
  },
  {
    id: 387,
    text: "Owning 55,000 of them, Ted Turner has the world’s largest private collection of ____.",
    answer: "Bison",
  },
  {
    id: 388,
    text: "The first item listed on eBay was a broken ____.",
    answer: "Laser Pointer",
  },
  {
    id: 389,
    text: "The Dutch version of Santa Claus has a helper named ____ Pete.",
    answer: "Black",
  },
  {
    id: 390,
    text: "Patented in 1890, U.S. Patent US435748 is for a mustache ____.",
    answer: "Guard",
  },
  {
    id: 391,
    text: "From the fine print for the original iPod Shuffle: “Do not ____ iPod Shuffle.”",
    answer: "Eat",
  },
  {
    id: 392,
    text: "Actual warning on Vidal Sassoon hair dryer: “Do not use while ____.”",
    answer: "Sleeping",
  },
  {
    id: 393,
    text: "From warning label on Extenze male enhancement supplement: “Do not use if ____.”",
    answer: "Pregnant",
  },
  {
    id: 394,
    text: "When visiting Paris, Texas check out their replica of the Eiffel Tower with a giant red ____ on top.",
    answer: "Cowboy Hat",
  },
  {
    id: 395,
    text: "Scooby-Doo’s sister, ____-Doo, is Scrappy-Doo’s mother.",
    answer: "Ruby",
  },
  {
    id: 396,
    text: "In 2012, a 26-year-old man from London went on a mission to lick every ____ in the United Kingdom.",
    answer: "Cathedral",
  },
  {
    id: 397,
    text: "Chosen, Shunned and Reckoning are all books in an unusual series about ____ vampires.",
    answer: "Amish",
  },
  {
    id: 398,
    text: "In 2013, a wealthy Michigan man bought the house next to his ex-wife and erected a giant bronze statue of a ____.",
    answer: "Middle Finger",
  },
  {
    id: 399,
    text: "There’s a novelty museum in Arlington, Massachusetts that only collects food that has been ____.",
    answer: "Burnt",
  },
  {
    id: 400,
    text: "As a young student in Buenos Aires, Pope Francis worked as a ____.",
    answer: "Bouncer",
  },
  {
    id: 401,
    text: "In 2012, a teenager from Weslaco, Texas claimed the reason he stabbed his friend was because a ____ made him do it.",
    answer: "Ouija Board",
  },
  {
    id: 402,
    text: "While visiting Roselawn, Indiana, check out the giant sundial made to resemble a ____.",
    answer: "Woman’s Leg",
  },
  {
    id: 403,
    text: "Phil Shaw is the founder of the bizarre sport called Extreme ____.",
    answer: "Ironing",
  },
  {
    id: 404,
    text: "On November 25, 2013, a 16-month-old Chinese girl underwent surgery to remove the unusual growth of a ____ in her ear canal.",
    answer: "Dandelion",
  },
  { id: 405, text: "Mike Tyson tweeted, “I’m a bad ____.”", answer: "Bowler" },
  {
    id: 406,
    text: "Gary Busey tweeted, “I wish my ears were ____.”",
    answer: "Cameras",
  },
  {
    id: 407,
    text: "In 2002, Bruce Willis sent 12,000 boxes of ____ to U.S. soldiers in Afghanistan.",
    answer: "Girl Scout Cookies",
  },
  {
    id: 408,
    text: "The first text message ever sent was by Neil Papworth in 1992. He texted, “____.”",
    answer: "Merry Christmas",
  },
  {
    id: 409,
    text: "In 2013, a 51-year-old Swedish inmate broke out of prison a day before his scheduled release so he could go see a ____.",
    answer: "Dentist",
  },
  {
    id: 410,
    text: "~~8-0 is the obscure emoticon that stands for ____.",
    answer: "Bad Hair Day",
  },
  {
    id: 411,
    text: "On November 12, 1970, George Thornton, a highway engineer in Oregon, had the unusual job of blowing up a ____.",
    answer: "Dead Whale",
  },
  {
    id: 412,
    text: "According to the nonfiction book The Man-Eating Tigers of Sundarbans, tiger urine “smells sort of like ____.”",
    answer: "Buttered Popcorn",
  },
  {
    id: 413,
    text: "Taylor Swift Tweeted “Thank you for tonight, Des Moines. I found endless amounts of ____ on my arms from hugging lots of you tonight.”",
    answer: "Glitter",
  },
  {
    id: 414,
    text: "Because of a metal shortage during the war, the Oscar statuettes given out during World War II were made out of ____.",
    answer: "Plaster",
  },
  {
    id: 415,
    text: "Richard Simmons’ Twitter handle @TheWeightSaint Tweeted: “At the airport ____ everyone.”",
    answer: "Hugging",
  },
  {
    id: 416,
    text: "In 2000, Australia had its largest ever online petition, which called for an end to rising ____ prices.",
    answer: "Beer",
  },
  {
    id: 417,
    text: "When Paul Nelson and Andrew Hunter climbed Britain’s highest mountain in 2006, they made an unusual discovery hidden behind a pile of stones. It was a ____.",
    answer: "Piano",
  },
  {
    id: 418,
    text: "The App of Icelanders is a phone app that warns you if the person you’re romantically interested in is a ____.",
    answer: "Relative",
  },
  {
    id: 419,
    text: "In school, Sylvester Stallone was voted by his teachers as Most Likely to Go To ____.",
    answer: "The Electric Chair",
  },
  {
    id: 420,
    text: "In 1965, Hasbro made a sad-looking, crying doll dressed in tattered rags called Little Miss ____.",
    answer: "No Name",
  },
  {
    id: 421,
    text: "The electric chair was invented by a professional ____ named Alfred Southwick.",
    answer: "Dentist",
  },
  {
    id: 422,
    text: "Although gross, chemist Sir Robert Cheseborough claimed he ate a spoonful of his invention, ____, every day.",
    answer: "Vaseline",
  },
  {
    id: 423,
    text: "The first thing eaten in outer space was ____.",
    answer: "Applesauce",
  },
  {
    id: 424,
    text: "The color of the Golden Gate Bridge is officially called ____ Orange.",
    answer: "International",
  },
  {
    id: 425,
    text: "According to the International Code of Disease, the code Y92250 is the code for “when a patient is injured in an ____.”",
    answer: "Art Gallery",
  },
  {
    id: 426,
    text: "Marcella Hazan is the culinary guru who pioneered the unusual technique of cooking duck with a ____.",
    answer: "Hair Dryer",
  },
  {
    id: 427,
    text: "The rare condition known as “argyria” causes people’s skin to ____.",
    answer: "Turn Blue",
  },
  {
    id: 428,
    text: "Prop comic Gallagher, known for smashing watermelons with a sledgehammer, earned a college degree in the field of ____.",
    answer: "Chemical Engineering",
  },
  {
    id: 429,
    text: "For a story he was reporting on in 1955, Dan Rather tried ____ for the first time.",
    answer: "Heroin",
  },
  {
    id: 430,
    text: "In India you can buy a cola named Gau Jal that includes the bizarre ingredient ____.",
    answer: "Cow Urine",
  },
  {
    id: 431,
    text: "The sports teams at Freeport High School in Illinois are oddly named after an inanimate object. The teams are called the Freeport ____.",
    answer: "Pretzels",
  },
  {
    id: 432,
    text: "In a study done by author Stefan Gates, 44% of adults admitted to eating ____.",
    answer: "Boogers",
  },
  {
    id: 433,
    text: "According to the National Oceanic and Atmospheric Association, small icebergs are officially called “growlers.” Medium icebergs go by the strange, two-word name “____.”",
    answer: "Bergy Bits",
  },
  {
    id: 434,
    text: "On January 13, 2014, U.S. Secretary of State John Kerry presented to Russian Foreign Minister Sergei Lavrov the odd gift of two very large ____.",
    answer: "Potatoes",
  },
  {
    id: 435,
    text: "During the mid to late-nineties, the town of Glastonbury was on a manhunt for the odd house intruder known as “The ____.”",
    answer: "Tickler",
  },
  {
    id: 436,
    text: "There is a riot police unit in the Russian town of Rostov-na-Donu that is composed entirely of ____.",
    answer: "Twins",
  },
  {
    id: 437,
    text: "In 2000, a mafia boss in an Italian prison escaped his cell using only ____.",
    answer: "Dental Floss",
  },
  {
    id: 438,
    text: "Located within the municipal boundaries of Kirkland Lake, Ontario, there lies the controversially named village of ____.",
    answer: "Swastika",
  },
  {
    id: 439,
    text: "Peter Gloystein, a German politician, resigned in 2005 after pouring wine on a ____.",
    answer: "Homeless Person",
  },
  {
    id: 440,
    text: "In 2003, Morocco made the highly unusual offer to send 2,000 ____ to assist the United States’ war effort in Iraq.",
    answer: "Monkeys",
  },
  {
    id: 441,
    text: "During an airline flight in 1995, Dr. Angus Wallace and Dr. Tom Wong performed a successful chest drain on a passenger using a rubber tube, brandy, and a ____.",
    answer: "Coat Hanger",
  },
  {
    id: 442,
    text: "Oddly enough, Albert Einstein’s eyeballs can be found in a ____ in New York City.",
    answer: "Safe Deposit Box",
  },
  {
    id: 443,
    text: "Dasypygal is an adjective meaning “having ____ buttocks.”",
    answer: "Hairy",
  },
  {
    id: 444,
    text: "In a 2013 poll conducted by Public Policy Polling, 27% of voters thought ____ should be subjected to a special tax for being so annoying.",
    answer: "Hipsters",
  },
  {
    id: 445,
    text: "When in Nepal, visit the villages Parsawa and Laxmipur, where you can enjoy the slightly off-putting 10 day ____ Festival.",
    answer: "Cursing",
  },
  {
    id: 446,
    text: "Reg Mellor is the reigning champion of a sport that just involves keeping a ____ in your pants.",
    answer: "Ferret",
  },
  {
    id: 447,
    text: "Before he became pope, Pope Pius II wrote an erotic novel titled The Tale of the ____.",
    answer: "Two Lovers",
  },
  {
    id: 448,
    text: "In the late 17th century, London was victimized by a man named Whipping Tom, who would randomly spank people and scream “____!”",
    answer: "Spanko",
  },
  {
    id: 449,
    text: "Romano Mussolini, son of the fascist dictator Benito Mussolini, did not follow in his father’s footsteps. Instead, he made his living as a ____.",
    answer: "Jazz Musician",
  },
  {
    id: 450,
    text: "The inventor of the chocolate chip cookie traded her recipe to Nestlé in exchange for a ____.",
    answer: "Lifetime Supply Of Chocolate",
  },
  {
    id: 451,
    text: "The first reporting on the Wright Brothers’ flights appeared not in a newspaper or on radio, but in a small journal dedicated to the topic of ____.",
    answer: "Beekeeping",
  },
  {
    id: 452,
    text: "Famed film director Alfred Hitchcock - the “Master of Suspense” - claimed, “I’m frightened of ____, worse than frightened, they revolt me.”",
    answer: "Eggs",
  },
  {
    id: 453,
    text: "A 2013 survey conducted by Playtex revealed that 8% of Canadians have had sex in a ____.",
    answer: "Canoe",
  },
  {
    id: 454,
    text: "The fishing company E21 makes a very peculiar fishing rod that is composed of 70% ____.",
    answer: "Carrots",
  },
  {
    id: 455,
    text: "A study published in the journal Anthrozoo reported that cows produce 5% more milk when they are given ____.",
    answer: "Names",
  },
  {
    id: 456,
    text: "A science student in Nepal has created an innovative solar panel that is far cheaper to make than a traditional solar panel, because it’s made with ____.",
    answer: "Human Hair",
  },
  {
    id: 457,
    text: "Since 1912, South Dakota State University’s homecoming week has culminated in a celebration oddly named ____ Day.",
    answer: "Hobo",
  },
  {
    id: 458,
    text: "Ruppy the beagle is a very unusual dog because he can ____.",
    answer: "Glow In The Dark",
  },
  {
    id: 459,
    text: "The Snickers candy bar was named after its creator’s ____.",
    answer: "Horse",
  },
  {
    id: 460,
    text: "After consuming antifreeze, a Maltese terrier in Australia had his life saved when vets then gave him ____ to drink.",
    answer: "Vodka",
  },
  {
    id: 461,
    text: "A Brazillian environmental group launched a campaign in 2009 to save the rainforest by urging people to pee in ____.",
    answer: "The Shower",
  },
  {
    id: 462,
    text: "A man in Proctor, Minnesota was arrested for driving a motorized ____ while drunk.",
    answer: "La-Z-Boy Chair",
  },
  {
    id: 463,
    text: "When on a spring break trip to Dongyang, China, be sure to try their eggs cooked in ____.",
    answer: "Young Boy Urine",
  },
  {
    id: 464,
    text: "George Frankel is the CEO of a Georgia-based company that will turn your dead relative’s ashes into ____.",
    answer: "A Reef",
  },
  {
    id: 465,
    text: "The staff at the Edible Canada restaurant posted a sign in their bathroom that instructed men to ____.",
    answer: "Sit When They Pee",
  },
  {
    id: 466,
    text: "In 2009, a Russian man shocked the medical world when it was discovered he had a 5 centimeter long ____ growing in his lung.",
    answer: "Tree Branch",
  },
  {
    id: 467,
    text: "The Backyard Brains company sells a device that lets you control ____ with your mobile phone.",
    answer: "Cockroaches",
  },
  {
    id: 468,
    text: "According to a Chinese myth, if a vampire comes across a sack of rice, he must ____.",
    answer: "Count Each Grain",
  },
  {
    id: 469,
    text: "On the northwest tower of the Washington National Cathedral, there hangs a gargoyle made to resemble ____.",
    answer: "Darth Vader",
  },
  {
    id: 470,
    text: "Lake Superior State University offers a bizarre license. The license entitles you to hunt ____.",
    answer: "Unicorns",
  },
  {
    id: 471,
    text: "When on the Hawaiian island of Molokai, be sure to visit the Hoolehua post office where you’re able to mail ____ without using a package.",
    answer: "Coconuts",
  },
  {
    id: 472,
    text: "A man from Enniskillen, Northern Ireland was sentenced to three months in prison for a fire he started while trying to turn ____ into gold.",
    answer: "His Poop",
  },
  {
    id: 473,
    text: "A study conducted at Tufts University by psychology grad student Nicholas Rule found that people have the ability to point out ____ in a crowd.",
    answer: "Mormons",
  },
  {
    id: 474,
    text: "Cambridge University economist Ha-Joon Chang holds an unpopular opinion. He insists that the ____ changed the world more than the Internet.",
    answer: "Washing Machine",
  },
  {
    id: 475,
    text: "When Charlie and the Chocolate Factory author Roald Dahl died, he was buried with snooker cues, burgundy, chocolate, pencils, and a ____.",
    answer: "Power Saw",
  },
  {
    id: 476,
    text: "A man in Watertown, New York, claims to have been happily married for over 25 years to his wife Teagan, who strangely is a ____.",
    answer: "Mannequin In A Wheelchair",
  },
  {
    id: 477,
    text: "Calum Wright, while a student at UC Berkeley, started an organization named “Students Against ____ in Trees.”",
    answer: "Hippies",
  },
  {
    id: 478,
    text: "New Mexico state senator Duncan Scott successfully got a bill passed in the New Mexico senate requiring psychiatrists testifying in court to wear a ____.",
    answer: "Wizard’s Hat",
  },
  {
    id: 479,
    text: "UC Irvine brought 6,084 students together in 2012 to break the world record for largest ____ ever.",
    answer: "Dodgeball Game",
  },
  {
    id: 480,
    text: "Highway construction in Iceland was delayed in 2013 after advocates claimed the project would destroy the natural land where ____ live and thrive.",
    answer: "Elves",
  },
  {
    id: 481,
    text: "A Rhode Island middle school discovered that some students were crushing Smarties candy and then snorting the dust. So they sent an email to parents, warning that a side effect of this activity could be ____ in their kids’ noses.",
    answer: "Maggots",
  },
  {
    id: 482,
    text: "When in the North Shore Mountains near Vancouver, British Columbia, be sure to climb the unusually named peak called ____ Mountain.",
    answer: "Unnecessary",
  },
  {
    id: 483,
    text: "According to a University of Barcelona study, surprisingly, 5% of people have absolutely no emotional response when they ____.",
    answer: "Listen To Music",
  },
  {
    id: 484,
    text: "In 1726, a British woman named Mary Toft convinced doctors that she had given birth to ____.",
    answer: "Rabbits",
  },
  {
    id: 485,
    text: "Mohammed Khurshid Hussain is in the Guinness Book of World Records because he is able to ____ very quickly with his nose.",
    answer: "Type",
  },
  {
    id: 486,
    text: "Patton actor George C. Scott refused to accept the Oscar he won in 1971, claiming the Academy Awards is a “two hour ____ parade.”",
    answer: "Meat",
  },
  {
    id: 487,
    text: "When in Marfa, Texas check out the unusual art piece shaped like a ____ store built right in the middle of the desert.",
    answer: "Prada",
  },
  {
    id: 488,
    text: "Ward Shelley and Alex Schweder’s art piece “In Orbit,” which was on display at a gallery in New York, featured two men living in a giant ____ for 10 days.",
    answer: "Hamster Wheel",
  },
  {
    id: 489,
    text: "Lindsay Lohan Tweeted: “____ is the best medicine.”",
    answer: "Working",
  },
  {
    id: 490,
    text: "Simon Cowell Tweeted: “Still not sure what a ____ is.”",
    answer: "Baby Shower",
  },
  {
    id: 491,
    text: "When in Lafayette, Louisiana, be sure to check out their somewhat erotic statue of a shirtless ____.",
    answer: "Fireman",
  },
  {
    id: 492,
    text: "In 1518, hundreds of people in Strasbourg became afflicted with a bizarre condition that rendered them unable to stop ____.",
    answer: "Dancing",
  },
  {
    id: 493,
    text: "Johnny Depp was made an honorary member of the Comanche Nation and given a descriptive Comanche name. His Comanche name, Mah-Woo-Meh, means ____.",
    answer: "Shape Shifter",
  },
  {
    id: 494,
    text: "In 2013 a zoo in China attempted to pass off a ____ as an African lion.",
    answer: "Large Dog",
  },
  {
    id: 495,
    text: "A Swedish man who works as a dishwasher receives disability benefits due to his unusual addiction to ____.",
    answer: "Heavy Metal Music",
  },
  {
    id: 496,
    text: "Blair Tolman wrote a self-help book called ____ for Under a Dollar: 301 Ideas.",
    answer: "Dating",
  },
  {
    id: 497,
    text: "Bill Bennett made news in 2004 when he was able to sell just a single, ordinary ____ on eBay.",
    answer: "Corn Flake",
  },
  {
    id: 498,
    text: "In 2004, the CEO of Blockbuster mailed Reed Hastings, the CEO of Netflix, an odd package. He sent him a ____.",
    answer: "Kitchen Sink",
  },
  {
    id: 499,
    text: "During the 1990s, teachers in North Korea were, oddly enough, required to know how to ____.",
    answer: "Play The Accordion",
  },
  {
    id: 500,
    text: "Instead of having guard dogs, police in rural parts of China’s Xinjiang Province use ____.",
    answer: "Geese",
  },
  {
    id: 501,
    text: "In 2013, the Romanian government, facing financial hardships, started taxing a group of people they had never taxed before. They started taxing ____.",
    answer: "Witches",
  },
  {
    id: 502,
    text: "In 2013, researchers at the University of Tokyo developed the incendiary reflection, a mirror that makes it look like you’re ____.",
    answer: "Smiling",
  },
  {
    id: 503,
    text: "Pam Anderson wrote a book of recipes with the title How to Cook Without a ____.",
    answer: "Book",
  },
  {
    id: 504,
    text: "In 2004, the Trane Corporation sold pillows in Japan that were designed to combat loneliness. They were shaped like a ____.",
    answer: "Woman’s Lap",
  },
  {
    id: 505,
    text: "Budget hotel chain Travelodge reported that between 2006 and 2007 about 95% of sleepwalkers found in their hotels were ____ men.",
    answer: "Naked",
  },
  {
    id: 506,
    text: "A man in Milford, Iowa, got fired from his job after he used a ____ to dislodge his Twix bar from the office vending machine.",
    answer: "Forklift",
  },
  {
    id: 507,
    text: "Actor Eddie Murphy released a dance song in 1982 titled “Boogie in ____.”",
    answer: "Your Butt",
  },
  {
    id: 508,
    text: "When in Laza, Spain, be sure to check out the annual festival where participants pelt each other with muddy rags full of ____.",
    answer: "Fire Ants",
  },
  {
    id: 509,
    text: "When visiting Christchurch, New Zealand, check out the $6 million cathedral made out of ____.",
    answer: "Cardboard",
  },
  {
    id: 510,
    text: "The mountain logo on a package of Toblerone chocolate contains a hidden image of a ____.",
    answer: "Bear",
  },
  {
    id: 511,
    text: "Coca-Cola once commissioned a video game from Atari called Pepsi ____.",
    answer: "Invaders",
  },
  {
    id: 512,
    text: "According to a 2010 study, one child in the U.S. was injured every 46 minutes by a ____.",
    answer: "Bounce House",
  },
  {
    id: 513,
    text: "Ahlgrim Acres is a nine hole miniature golf course oddly located in an Illinois ____.",
    answer: "Funeral Home",
  },
  {
    id: 514,
    text: "Psycho was the first American movie to show a ____.",
    answer: "Toilet Flushing",
  },
  {
    id: 515,
    text: "One of Kim Jong Il’s many titles was “Invicible and Ever-Triumphant General and Highest Incarnation of the Revolutionary Comradely ____”.",
    answer: "Love",
  },
  {
    id: 516,
    text: "Miraculously, a man in Longview, Washington survived a harrowing event in 2014 when he was stuck in a ____ for ten seconds.",
    answer: "Wood Chipper",
  },
  {
    id: 517,
    text: "Country singer Trace Adkins went into rehab after fighting a ____ while on a Jamaican cruise.",
    answer: "Trace Adkins Impersonator",
  },
  {
    id: 518,
    text: "Pentheraphobia is the constant fear of your ____.",
    answer: "Mother-In-Law",
  },
  {
    id: 519,
    text: "The New York Times was forced to issue a correction after they incorrectly identified the Nintendo characters Mario and Luigi as ____ instead of plumbers.",
    answer: "Janitors",
  },
  {
    id: 520,
    text: "PETA has asked officials in Punxsutawney, Pennsylvania to replace Punxsutawney Phil, the Groundhog Day groundhog, with ____.",
    answer: "An Animatronic Groundhog",
  },
  {
    id: 521,
    text: "The real name of the Internet’s famous Grumpy Cat is ____.",
    answer: "Tardar Sauce",
  },
  {
    id: 522,
    text: "In autumn 2013, a company that owns parking lots in England temporarily allowed drivers to pay for parking not with money, but with ____.",
    answer: "Chestnuts",
  },
  {
    id: 523,
    text: "Gloucestershire, England is home to the Cotswold Olimpicks, the highlight of which is the traditional ____-kicking competition.",
    answer: "Shin",
  },
  {
    id: 524,
    text: "Moviegoers who use their cell phones at the Prince Charles Cinema in London are escorted out by people dressed as ____.",
    answer: "Ninjas",
  },
  {
    id: 525,
    text: "Hugh Grant’s full name is Hugh John ____ Grant.",
    answer: "Mungo",
  },
  {
    id: 526,
    text: "Used in medical studies, a robot at the UK’s Health and Safety Laboratory goes by the name ____ Larry.",
    answer: "Vomiting",
  },
  {
    id: 527,
    text: "In 1988, George H. W. Bush celebrated Halloween by dressing up as ____.",
    answer: "Himself",
  },
  {
    id: 528,
    text: "The unusual Chick and Sophie Major memorial scholarships are awarded to high school students who are good at ____.",
    answer: "Duck Calls",
  },
  {
    id: 529,
    text: "A man in Florida was arrested for calling 911 to complain that he wasn’t allowed to bring his ____ into a strip club.",
    answer: "Cat",
  },
  {
    id: 530,
    text: "Chad Orzel wrote the book How to Teach ____ to Your Dog.",
    answer: "Physics",
  },
  {
    id: 531,
    text: "The 1995 Diagram Prize for Oddest Book Title of the Year went to the book Reusing Old ____.",
    answer: "Graves",
  },
  {
    id: 532,
    text: "When soccer player Stefan Schwarz signed with Sunderland in 1999, the team made sure that his contract specifically prohibited him from traveling to ____.",
    answer: "Outer Space",
  },
  {
    id: 533,
    text: "Evergreen Cemetery includes an odd statue of Jesus wearing ____.",
    answer: "Cowboy Boots",
  },
  {
    id: 534,
    text: "Benjamin Moore paint color 787 has the strange name Grandma’s ____.",
    answer: "Sweater",
  },
  {
    id: 535,
    text: "A Florida woman returned home one day in 2012 to discover that, strangely, her ____ had been stolen while neighbors just watched it happen.",
    answer: "Driveway",
  },
  {
    id: 536,
    text: "On December 3, 2009, and March 30, 2010, rapper Eminem Tweeted a photo proving he was surprisingly really good at ____.",
    answer: "Donkey Kong",
  },
  {
    id: 537,
    text: "In 1990, before “Everybody Loves Raymond,” actor Peter Boyle starred in a failed TV pilot called ____ about a cop who turns into a talking bulldog.",
    answer: "Poochinski",
  },
  {
    id: 538,
    text: "The first and only dog to be given rank in the United States Armed Forces was named Sergeant ____.",
    answer: "Stubby",
  },
  {
    id: 539,
    text: "The lead singer of the heavy metal band Hatebeak is ____.",
    answer: "A Parrot",
  },
  {
    id: 540,
    text: "King Henry IV of Castile had the embarrassing nickname “Henry the ____.”",
    answer: "Impotent",
  },
  {
    id: 541,
    text: "You are experiencing the Mariko Aoki phenomenon when you have the urge to poop while ____.",
    answer: "In A Bookstore",
  },
  {
    id: 542,
    text: "Metrophilia is sexual arousal caused by ____.",
    answer: "Poetry",
  },
  {
    id: 543,
    text: "The band Queen’s original name was ____.",
    answer: "Smile",
  },
  {
    id: 544,
    text: "The name for a group of porcupines is a ____.",
    answer: "Prickle",
  },
  {
    id: 545,
    text: "The secret code name for the project to invent the first microwave oven in the 1940s was ____.",
    answer: "Speedy Weenie",
  },
  {
    id: 546,
    text: "The name of the man on the Quaker Oats label is ____.",
    answer: "Larry",
  },
  {
    id: 547,
    text: "The original name for Pepsi was ____.",
    answer: "Brad’s Drink",
  },
  {
    id: 548,
    text: "About 180 miles south of New Zealand, at the coordinates 50’36.25’S 165’58.38’E, lies this oddly named island: ____ Island.",
    answer: "Disappointment",
  },
  {
    id: 549,
    text: "The name of the Star Trek starship in creator Gene Roddenberry’s original script was ____.",
    answer: "Yorktown",
  },
  {
    id: 550,
    text: "In the U.S., the original name of the game bingo was ____.",
    answer: "Beano",
  },
  {
    id: 551,
    text: "Dr. Edgar Parker legally changed his first name to ____ in order to help his dental practice.",
    answer: "Painless",
  },
  {
    id: 552,
    text: "Under the Marine Corps Uniform regulation code MCO P1020.34F, a male marine is not allowed to carry a ____ while in uniform.",
    answer: "Umbrella",
  },
  {
    id: 553,
    text: "Strange brand name for the cigarettes sold by The Enlightened Tobacco Company in the 1990s was ____.",
    answer: "Death",
  },
  {
    id: 554,
    text: "Brand name of the (patented) synthetic testicles for pets is ____.",
    answer: "Neuticles",
  },
  {
    id: 555,
    text: "Dr. Francis M. Fesmire’s surefire remedy for stopping your hiccups is ____.",
    answer: "Rectal Massage",
  },
  {
    id: 556,
    text: "Wilma Flintstone’s maiden name is ____.",
    answer: "Slaghoople",
  },
  {
    id: 557,
    text: "The name for the random symbols used to indicate swearing in comic strips is ____.",
    answer: "Grawlix",
  },
  {
    id: 558,
    text: "Jim Henson’s original name for Fraggle Rock was ____.",
    answer: "Woozle World",
  },
  {
    id: 559,
    text: "Item that teachers at Mounts Bay Academy in England were banned from using in 2014 was ____.",
    answer: "Red Pens",
  },
  {
    id: 560,
    text: "The Michelin Man’s strange, official name is ____.",
    answer: "Bibendum",
  },
  {
    id: 561,
    text: "Former first lady Barbara Bush wrote an official apology letter to this fictional character in 1990: ____.",
    answer: "Marge Simpson",
  },
  {
    id: 562,
    text: "Name of the experimental grilled pineapple sandwich from McDonald’s that lost out in a sales contest to the Filet-O-Fish was the ____.",
    answer: "Hula Burger",
  },
  {
    id: 563,
    text: "Name of the Rhode Island School of Design’s penis-shaped hockey mascot is ____.",
    answer: "Scrotie",
  },
  {
    id: 564,
    text: "What South Africans call traffic lights: ____.",
    answer: "Robots",
  },
  {
    id: 565,
    text: "Harry Houdini once threatened to shoot all ____.",
    answer: "Psychics",
  },
  { id: 566, text: "Donald Duck’s middle name is ____.", answer: "Fauntleroy" },
  { id: 567, text: "Michael J. Fox’s middle name is ____.", answer: "Andrew" },
  {
    id: 568,
    text: "At 65% alcohol by volume, Brewmeister brews the world’s strongest beer, which goes by the name ____.",
    answer: "Armageddon",
  },
  { id: 569, text: "The shape of wombat poop is a ____.", answer: "Cube" },
  {
    id: 570,
    text: "Samsung started out as a company that made ____.",
    answer: "Noodles",
  },
  {
    id: 571,
    text: "Dr. Seuss is credited with coining this common derogatory term in his 1950 book If I Ran the Zoo: ____.",
    answer: "Nerd",
  },
  {
    id: 572,
    text: "The name of the dildo resembling Queen Elizabeth II that’s sold by the company Masturpieces is ____.",
    answer: "Buckingham Phallus",
  },
  {
    id: 573,
    text: "The name of the first chimp sent into space was ____.",
    answer: "Ham",
  },
  {
    id: 574,
    text: "The U.S. occupation with the highest percentage of white people is ____.",
    answer: "Veterinarian",
  },
  {
    id: 575,
    text: "Miley Cyrus’s real first name is ____.",
    answer: "Destiny",
  },
  {
    id: 576,
    text: "The fastest-growing baby name for girls in 2012 was ____.",
    answer: "Arya",
  },
  {
    id: 577,
    text: "Name of the company that makes “bullet resistant groin protectors” is ____.",
    answer: "NutShellz",
  },
  { id: 578, text: "Cap’n Crunch’s first name is ____.", answer: "Horatio" },
  {
    id: 579,
    text: "Occupation with the highest divorce rate, according to the 2000 U.S. Census, is ____.",
    answer: "Dancer",
  },
  {
    id: 580,
    text: "Current brand-name product that was originally called “Baby Gays” in 1926 is ____.",
    answer: "Q-Tips",
  },
  {
    id: 581,
    text: "The original brand name for Kool-Aid was ____.",
    answer: "Fruit Smack",
  },
  {
    id: 582,
    text: "The name of the Kermit the Frog-inspired cologne made by January Productions in 1995 was ____.",
    answer: "Amphibia",
  },
  {
    id: 583,
    text: "The original name for the search engine that became Google was ____.",
    answer: "BackRub",
  },
  {
    id: 584,
    text: "The Oxford Dictionaries’ “word of the year” for 2013 was ____.",
    answer: "Selfie",
  },
  {
    id: 585,
    text: "What the British call the dance that Americans call the “Hokey Pokey” is the ____.",
    answer: "Hokey Cokey",
  },
  {
    id: 586,
    text: "The name of the dog that won the 2012 World’s Ugliest Dog Competition was ____.",
    answer: "Mugly",
  },
  {
    id: 587,
    text: "Product name of the “gas neutralizer” pad that you insert into your underwear, made by the Solutions That Stick company, is ____.",
    answer: "Subtle Butt",
  },
  {
    id: 588,
    text: "Cause of death of an Indian stuntman who died while crossing a river on a zip-line attached only to his ponytail was ____.",
    answer: "Heart Attack",
  },
  {
    id: 589,
    text: "When Milton Bradley first acquired the rights to it, the game Twister was called ____.",
    answer: "Pretzel",
  },
  {
    id: 590,
    text: "Jimmy Hoffa’s unusual middle name was ____.",
    answer: "Riddle",
  },
  {
    id: 591,
    text: "Brand name of the “criminal dolls” for children with names like Dickie the Dealer and Bonnie Anne Bribe is ____.",
    answer: "Thuggies",
  },
];
