module.exports = [
  {
    id: 1,
    text: "In 2012, a man in Oregon was arrested for DUI while driving a ____.",
    answer: "Lawn Mower",
  },
  {
    id: 2,
    text: "The intense fear of ____ is known as 'Arachibutyrophobia'.",
    answer: "Peanut Butter",
  },
  {
    id: 3,
    text: "A company in Japan sells a doll that looks like ____.",
    answer: "Obama",
  },
  {
    id: 4,
    text: "In the 19th century, ketchup was sold as medicine to cure ____.",
    answer: "Diarrhea",
  },
  {
    id: 5,
    text: "The first item sold on eBay was a broken ____.",
    answer: "Laser Pointer",
  },
  {
    id: 6,
    text: "In 2013, a pig in Australia stole 18 beers from a campsite, got drunk, and fought a ____.",
    answer: "Cow",
  },
  {
    id: 7,
    text: "A 2009 study found that cows who have ____ produce more milk.",
    answer: "Names",
  },
  {
    id: 8,
    text: "The official state sport of Maryland is ____.",
    answer: "Jousting",
  },
  {
    id: 9,
    text: "Banging your head against a wall burns ____ calories an hour.",
    answer: "150",
  },
  {
    id: 10,
    text: "In Switzerland, it is illegal to own just one ____.",
    answer: "Guinea Pig",
  },
  { id: 11, text: "A group of pugs is called a ____.", answer: "Grumble" },
  {
    id: 12,
    text: "In 2015, a silver coin with the image of ____ was minted in New Zealand.",
    answer: "Pizza",
  },
  {
    id: 13,
    text: "The dot over the letter 'i' is called a ____.",
    answer: "Tittle",
  },
  {
    id: 14,
    text: "Before toilet paper was invented, Americans used ____.",
    answer: "Corn Cobs",
  },
  {
    id: 15,
    text: "A group of flamingos is called a ____.",
    answer: "Flamboyance",
  },
  {
    id: 16,
    text: "In 2014, a woman was arrested in Pennsylvania for shoplifting 50 bottles of ____.",
    answer: "Air Freshener",
  },
  {
    id: 17,
    text: "The inventor of the Pringles can is buried in a ____.",
    answer: "Pringles Can",
  },
  {
    id: 18,
    text: "In 1386, a pig in France was executed by public hanging for the murder of a ____.",
    answer: "Child",
  },
  {
    id: 19,
    text: "Human thigh bones are stronger than ____.",
    answer: "Concrete",
  },
  {
    id: 20,
    text: "The national animal of Scotland is the ____.",
    answer: "Unicorn",
  },
  {
    id: 21,
    text: "In 2006, an Australian man tried to sell ____ on eBay.",
    answer: "New Zealand",
  },
  {
    id: 22,
    text: "The tiny plastic piece at the end of a shoelace is called an ____.",
    answer: "Aglet",
  },
  {
    id: 23,
    text: "Coprastastaphobia is the fear of ____.",
    answer: "Constipation",
  },
  {
    id: 24,
    text: "In 1923, jockey Frank Hayes won a race at Belmont Park despite being ____.",
    answer: "Dead",
  },
  {
    id: 25,
    text: "The first webcam was invented to check the status of a ____.",
    answer: "Coffee Pot",
  },
  { id: 26, text: "A group of ferrets is called a ____.", answer: "Business" },
  {
    id: 27,
    text: "In 1998, Sony accidentally sold 700,000 camcorders that could see through ____.",
    answer: "Clothes",
  },
  {
    id: 28,
    text: "The fear of long words is called ____.",
    answer: "Hippopotomonstrosesquippedaliophobia",
  },
  {
    id: 29,
    text: "Billy goats urinate on their own ____ to attract females.",
    answer: "Heads",
  },
  {
    id: 30,
    text: "In 2011, a woman bought a non-visible piece of art for $10,000 made entirely of ____.",
    answer: "Air",
  },
  {
    id: 31,
    text: "The electric chair was invented by a ____.",
    answer: "Dentist",
  },
  {
    id: 32,
    text: "A duel between three people is called a ____.",
    answer: "Truel",
  },
  {
    id: 33,
    text: "In 2008, a man in Zimbabwe was arrested for 'criminal nuisance' after he was caught ____ at a police car.",
    answer: "Laughing",
  },
  {
    id: 34,
    text: "The King of Hearts is the only king without a ____.",
    answer: "Mustache",
  },
  {
    id: 35,
    text: "During WWII, the crew of a British submarine found a ____ inside a torpedo tube.",
    answer: "Reindeer",
  },
  {
    id: 36,
    text: "The Twitter bird's official name is ____.",
    answer: "Larry",
  },
  {
    id: 37,
    text: "In 2016, a man in Florida threw a ____ through a drive-thru window.",
    answer: "Alligator",
  },
  {
    id: 38,
    text: "A single strand of spaghetti is called a ____.",
    answer: "Spaghetto",
  },
  {
    id: 39,
    text: "The space between your eyebrows is called the ____.",
    answer: "Glabella",
  },
  {
    id: 40,
    text: "In 2012, a Swedish man was arrested for trying to split atoms in his ____.",
    answer: "Kitchen",
  },
  {
    id: 41,
    text: "The plastic thing inside a pizza box is called a ____.",
    answer: "Pizza Saver",
  },
  {
    id: 42,
    text: "A group of porcupines is called a ____.",
    answer: "Prickle",
  },
  {
    id: 43,
    text: "In 1907, an ad campaign for Corn Flakes offered a free ____ to anyone who bought a box.",
    answer: "Woman",
  },
  {
    id: 44,
    text: "The fear of vegetables is called ____.",
    answer: "Lachanophobia",
  },
  {
    id: 45,
    text: "In 2015, a man in Germany broke up with his girlfriend and sawed all their belongings in ____.",
    answer: "Half",
  },
  {
    id: 46,
    text: "The smell of rain hitting dry ground is called ____.",
    answer: "Petrichor",
  },
  {
    id: 47,
    text: "In 2017, a man in China tried to pay for a new car using only ____.",
    answer: "Coins",
  },
  {
    id: 48,
    text: "The little lump of flesh in front of your ear canal is called the ____.",
    answer: "Tragus",
  },
  { id: 49, text: "A group of crows is called a ____.", answer: "Murder" },
  {
    id: 50,
    text: "In 2010, a man in Korea married his ____.",
    answer: "Pillow",
  },
  {
    id: 51,
    text: "The fear of belly buttons is called ____.",
    answer: "Omphalophobia",
  },
  {
    id: 52,
    text: "In 2013, a man in Brazil was killed when a ____ fell through his roof.",
    answer: "Cow",
  },
  {
    id: 53,
    text: "The indentation between your nose and upper lip is called the ____.",
    answer: "Philtrum",
  },
  {
    id: 54,
    text: "In 2007, a man in Bosnia claimed he could stick ____ to his face.",
    answer: "Cans",
  },
  { id: 55, text: "A group of jellyfish is called a ____.", answer: "Smack" },
  {
    id: 56,
    text: "The fear of being without your mobile phone is called ____.",
    answer: "Nomophobia",
  },
  {
    id: 57,
    text: "In 2014, a man in the UK legally changed his name to ____.",
    answer: "Bacon Double Cheeseburger",
  },
  {
    id: 58,
    text: "The wire cage that holds the cork on a champagne bottle is called a ____.",
    answer: "Muselet",
  },
  {
    id: 59,
    text: "In 2011, a woman in the US was arrested for riding a ____ while intoxicated.",
    answer: "Horse",
  },
  { id: 60, text: "The fear of chins is called ____.", answer: "Geniophobia" },
  { id: 61, text: "Wombat poop is shaped like ____.", answer: "Cubes" },
  {
    id: 62,
    text: "Chainsaws were originally invented to help with ____.",
    answer: "Childbirth",
  },
  {
    id: 63,
    text: "Astronauts say the moon smells like ____.",
    answer: "Gunpowder",
  },
  {
    id: 64,
    text: "High heels were originally invented for ____.",
    answer: "Men",
  },
  { id: 65, text: "Cotton candy was invented by a ____.", answer: "Dentist" },
  {
    id: 66,
    text: "The technical name for the hashtag symbol (#) is ____.",
    answer: "Octothorpe",
  },
  { id: 67, text: "Barbie's middle name is ____.", answer: "Millicent" },
  {
    id: 68,
    text: "Trypophobia is the fear of clustered ____.",
    answer: "Holes",
  },
  {
    id: 69,
    text: "Sea otters hold ____ while sleeping to keep from drifting apart.",
    answer: "Hands",
  },
  {
    id: 70,
    text: "The inventor of the Frisbee was cremated and turned into a ____.",
    answer: "Frisbee",
  },
  { id: 71, text: "A group of rhinos is called a ____.", answer: "Crash" },
  {
    id: 72,
    text: "Originally, 3 Musketeers bars included chocolate, vanilla, and ____.",
    answer: "Strawberry",
  },
  {
    id: 73,
    text: "Hawaiian pizza was actually invented in ____.",
    answer: "Canada",
  },
  {
    id: 74,
    text: "The CIA once spent $20 million on a cat equipped with a ____.",
    answer: "Microphone",
  },
  {
    id: 75,
    text: "Bubble wrap was originally invented to be used as ____.",
    answer: "Wallpaper",
  },
  {
    id: 76,
    text: "Nintendo was founded in 1889 as a ____ company.",
    answer: "Playing Card",
  },
  {
    id: 77,
    text: "The Eiffel Tower grows about 6 inches in the ____.",
    answer: "Summer",
  },
  { id: 78, text: "A snail can sleep for ____ years.", answer: "Three" },
  {
    id: 79,
    text: "____ have fingerprints almost indistinguishable from humans.",
    answer: "Koalas",
  },
  {
    id: 80,
    text: "Botanically speaking, bananas are classified as ____.",
    answer: "Berries",
  },
  { id: 81, text: "A group of lemurs is called a ____.", answer: "Conspiracy" },
  {
    id: 82,
    text: "The King of England legally owns all the ____ in the River Thames.",
    answer: "Swans",
  },
  {
    id: 83,
    text: "Reno, Nevada is actually west of ____, California.",
    answer: "Los Angeles",
  },
  { id: 84, text: "The US state closest to Africa is ____.", answer: "Maine" },
  {
    id: 85,
    text: "Russia has a larger surface area than ____.",
    answer: "Pluto",
  },
  {
    id: 86,
    text: "Saudi Arabia imports camels from ____.",
    answer: "Australia",
  },
  { id: 87, text: "A baby puffin is called a ____.", answer: "Puffling" },
  {
    id: 88,
    text: "Talkeetna, Alaska elected a ____ as mayor for 20 years.",
    answer: "Cat",
  },
  {
    id: 89,
    text: "The Lyrebird is famous for mimicking the sound of ____.",
    answer: "Chainsaws",
  },
  {
    id: 90,
    text: "A group of pandas is called an ____.",
    answer: "Embarrassment",
  },
  {
    id: 91,
    text: "In 2009, Stephen Hawking threw a party for ____, but no one showed up.",
    answer: "Time Travelers",
  },
  {
    id: 92,
    text: "There are more ____ flamingos in the world than real ones.",
    answer: "Plastic",
  },
  {
    id: 93,
    text: "An average cumulus cloud weighs about 1.1 million ____.",
    answer: "Pounds",
  },
  {
    id: 94,
    text: "In 2015, a sheep named Chris was found with ____ pounds of wool.",
    answer: "90",
  },
  {
    id: 95,
    text: "The first mechanical alarm clock could only ring at ____.",
    answer: "4 AM",
  },
  { id: 96, text: "A group of frogs is called an ____.", answer: "Army" },
  {
    id: 97,
    text: "In 2014, an exchange student in Germany got stuck inside a giant stone statue of a ____.",
    answer: "Vagina",
  },
  { id: 98, text: "A group of stingrays is called a ____.", answer: "Fever" },
  {
    id: 99,
    text: "In 2011, a monkey was arrested in Pakistan for crossing the ____.",
    answer: "Border",
  },
  { id: 100, text: "A group of zebras is called a ____.", answer: "Dazzle" },
  {
    id: 101,
    text: "In 2015, a man sued himself for hitting himself with a ____.",
    answer: "Boomerang",
  },
  {
    id: 102,
    text: "A group of rattlesnakes is called a ____.",
    answer: "Rhumba",
  },
  { id: 103, text: "Turophobia is the fear of ____.", answer: "Cheese" },
  {
    id: 104,
    text: "Nomophobia is the fear of being without your ____.",
    answer: "Mobile Phone",
  },
  {
    id: 105,
    text: "In 2014, a man in the UK legally changed his name to ____.",
    answer: "Bacon Double Cheeseburger",
  },
  {
    id: 106,
    text: "The wire cage that holds the cork on a champagne bottle is called a ____.",
    answer: "Muselet",
  },
  { id: 107, text: "Pogonophobia is the fear of ____.", answer: "Beards" },
  {
    id: 108,
    text: "Omphalophobia is the fear of ____.",
    answer: "Belly Buttons",
  },
  {
    id: 109,
    text: "Oxford University is older than the ____ Empire.",
    answer: "Aztec",
  },
  {
    id: 110,
    text: "____ can hold their breath longer than dolphins.",
    answer: "Sloths",
  },
  { id: 111, text: "A group of owls is called a ____.", answer: "Parliament" },
  {
    id: 112,
    text: "In 1923, a jockey named Frank Hayes won a race despite being ____.",
    answer: "Dead",
  },
  {
    id: 113,
    text: "The plastic tip at the end of a shoelace is called an ____.",
    answer: "Aglet",
  },
  {
    id: 114,
    text: "The fear of being tickled by feathers is called ____.",
    answer: "Pteronophobia",
  },
  { id: 115, text: "A baby porcupine is called a ____.", answer: "Porcupette" },
  {
    id: 116,
    text: "In the 18th century, wealthy British garden owners would hire people to be ornamental ____.",
    answer: "Hermits",
  },
  {
    id: 117,
    text: "The dot over the letter 'j' is called a ____.",
    answer: "Tittle",
  },
  { id: 118, text: "A group of crows is called a ____.", answer: "Murder" },
  {
    id: 119,
    text: "The space between your eyebrows is called the ____.",
    answer: "Glabella",
  },
  {
    id: 120,
    text: "In 2007, a woman in the US married the ____.",
    answer: "Eiffel Tower",
  },
  {
    id: 121,
    text: "The fear of long words is ironically called ____.",
    answer: "Hippopotomonstrosesquippedaliophobia",
  },
  {
    id: 122,
    text: "A single strand of spaghetti is called a ____.",
    answer: "Spaghetto",
  },
  {
    id: 123,
    text: "The tiny pocket in jeans was originally designed to hold ____.",
    answer: "Watches",
  },
  {
    id: 124,
    text: "The smell of rain hitting dry soil is called ____.",
    answer: "Petrichor",
  },
  { id: 125, text: "A group of ferrets is called a ____.", answer: "Business" },
  {
    id: 126,
    text: "The indentation between your nose and upper lip is called the ____.",
    answer: "Philtrum",
  },
  {
    id: 127,
    text: "In 1386, a pig in France was executed by public hanging for the murder of a ____.",
    answer: "Child",
  },
  {
    id: 128,
    text: "The fear of buttons is called ____.",
    answer: "Koumpounophobia",
  },
  { id: 129, text: "A group of jellyfish is called a ____.", answer: "Smack" },
  {
    id: 130,
    text: "The metal band that holds a pencil eraser in place is called a ____.",
    answer: "Ferrule",
  },
  {
    id: 131,
    text: "In 2012, a man in Sweden was arrested for trying to split atoms in his ____.",
    answer: "Kitchen",
  },
  {
    id: 132,
    text: "The fear of cooking is called ____.",
    answer: "Mageirocophobia",
  },
  { id: 133, text: "A group of stingrays is called a ____.", answer: "Fever" },
  {
    id: 134,
    text: "The cardboard sleeve on a coffee cup is called a ____.",
    answer: "Zarf",
  },
  {
    id: 135,
    text: "In 2016, a man in Florida threw a ____ through a drive-thru window.",
    answer: "Alligator",
  },
  {
    id: 136,
    text: "The fear of palindromes is called ____.",
    answer: "Aibohphobia",
  },
  { id: 137, text: "A group of hippos is called a ____.", answer: "Bloat" },
  {
    id: 138,
    text: "The symbol used for division (÷) is technically called an ____.",
    answer: "Obelus",
  },
  {
    id: 139,
    text: "In 2011, a woman bought a piece of 'invisible art' for $10,000 made entirely of ____.",
    answer: "Air",
  },
  { id: 140, text: "The fear of knees is called ____.", answer: "Genuphobia" },
  {
    id: 141,
    text: "A group of ravens is called an ____.",
    answer: "Unkindness",
  },
  {
    id: 142,
    text: "The infinity symbol (∞) is technically called a ____.",
    answer: "Lemniscate",
  },
  {
    id: 143,
    text: "In 2008, a man in Zimbabwe was arrested for 'criminal nuisance' after he was caught ____ at a police car.",
    answer: "Laughing",
  },
  {
    id: 144,
    text: "The fear of the color yellow is called ____.",
    answer: "Xanthophobia",
  },
  { id: 145, text: "A group of zebras is called a ____.", answer: "Dazzle" },
  {
    id: 146,
    text: "The white, crescent-shaped area at the base of a fingernail is called the ____.",
    answer: "Lunule",
  },
  {
    id: 147,
    text: "In 2015, a man in Germany sawed all his belongings in ____ after a breakup.",
    answer: "Half",
  },
  { id: 148, text: "The fear of flutes is called ____.", answer: "Aulophobia" },
  { id: 149, text: "A group of frogs is called an ____.", answer: "Army" },
  {
    id: 150,
    text: "The little lump of flesh in front of your ear canal is called the ____.",
    answer: "Tragus",
  },
  {
    id: 151,
    text: "In 2013, a pig in Australia stole 18 beers and got into a fight with a ____.",
    answer: "Cow",
  },
  {
    id: 152,
    text: "The fear of vegetables is called ____.",
    answer: "Lachanophobia",
  },
  {
    id: 153,
    text: "A group of lemurs is called a ____.",
    answer: "Conspiracy",
  },
  {
    id: 154,
    text: "The day after tomorrow is technically called ____.",
    answer: "Overmorrow",
  },
  {
    id: 155,
    text: "In 2014, a woman was arrested in Pennsylvania for shoplifting 50 bottles of ____.",
    answer: "Air Freshener",
  },
  { id: 156, text: "The fear of chins is called ____.", answer: "Geniophobia" },
  { id: 157, text: "A group of wombats is called a ____.", answer: "Wisdom" },
  {
    id: 158,
    text: "The rumble your stomach makes when you are hungry is called ____.",
    answer: "Borborygmus",
  },
  {
    id: 159,
    text: "In 2009, Stephen Hawking threw a party for ____, but no one showed up.",
    answer: "Time Travelers",
  },
  {
    id: 160,
    text: "The fear of beautiful women is called ____.",
    answer: "Venustraphobia",
  },
  {
    id: 161,
    text: "Cap'n Crunch's full name is ____ Magellan Crunch.",
    answer: "Horatio",
  },
  { id: 162, text: "The Cookie Monster's real name is ____.", answer: "Sid" },
  {
    id: 163,
    text: "The Michelin Man's actual name is ____.",
    answer: "Bibendum",
  },
  { id: 164, text: "Hippo milk is naturally ____.", answer: "Pink" },
  { id: 165, text: "Slugs have four ____.", answer: "Noses" },
  { id: 166, text: "An octopus has three ____.", answer: "Hearts" },
  { id: 167, text: "A baby echidna is called a ____.", answer: "Puggle" },
  { id: 168, text: "Platypuses have no ____.", answer: "Stomachs" },
  { id: 169, text: "A shrimp's heart is located in its ____.", answer: "Head" },
  {
    id: 170,
    text: "Kangaroo rats can go their entire lives without drinking ____.",
    answer: "Water",
  },
  {
    id: 171,
    text: "The Turritopsis dohrnii is a species of jellyfish that is biologically ____.",
    answer: "Immortal",
  },
  {
    id: 172,
    text: "A blue whale's heart is the size of a ____.",
    answer: "Car",
  },
  {
    id: 173,
    text: "An ostrich's eye is bigger than its ____.",
    answer: "Brain",
  },
  {
    id: 174,
    text: "Underneath their fur, polar bears have ____ skin.",
    answer: "Black",
  },
  {
    id: 175,
    text: "Cows can walk up stairs, but they cannot walk ____.",
    answer: "Down",
  },
  {
    id: 176,
    text: "It is physically impossible for pigs to look up at the ____.",
    answer: "Sky",
  },
  { id: 177, text: "Butterflies taste with their ____.", answer: "Feet" },
  {
    id: 178,
    text: "Elephants are the only mammal that cannot ____.",
    answer: "Jump",
  },
  {
    id: 179,
    text: "When exiting a cave, bats always turn ____.",
    answer: "Left",
  },
  { id: 180, text: "A crocodile cannot stick out its ____.", answer: "Tongue" },
  { id: 181, text: "Starfish have no ____.", answer: "Brain" },
  {
    id: 182,
    text: "Honey is the only food that never ____.",
    answer: "Spoils",
  },
  { id: 183, text: "Peanuts are not nuts, they are ____.", answer: "Legumes" },
  {
    id: 184,
    text: "Almonds are a member of the ____ family.",
    answer: "Peach",
  },
  { id: 185, text: "Apples float because they are 25% ____.", answer: "Air" },
  {
    id: 186,
    text: "Ripe cranberries will ____ if you drop them.",
    answer: "Bounce",
  },
  {
    id: 187,
    text: "Genetically, mushrooms are more closely related to ____ than plants.",
    answer: "Humans",
  },
  {
    id: 188,
    text: "Corn always grows in an ____ number of rows.",
    answer: "Even",
  },
  { id: 189, text: "Originally, carrots were ____.", answer: "Purple" },
  {
    id: 190,
    text: "Artificial vanilla flavoring (Castoreum) comes from a gland in a beaver's ____.",
    answer: "Butt",
  },
  {
    id: 191,
    text: "The red food dye 'Carmine' is made from crushed ____.",
    answer: "Beetles",
  },
  {
    id: 192,
    text: "The shiny coating on jelly beans (Shellac) is made from ____ poop.",
    answer: "Bug",
  },
  {
    id: 193,
    text: "France's longest border is shared with ____.",
    answer: "Brazil",
  },
  {
    id: 194,
    text: "Canada has more ____ than the rest of the world combined.",
    answer: "Lakes",
  },
  { id: 195, text: "China has only one ____.", answer: "Time Zone" },
  {
    id: 196,
    text: "The official birth rate of Vatican City is ____.",
    answer: "Zero",
  },
  { id: 197, text: "Napoleon was actually of ____ height.", answer: "Average" },
  {
    id: 198,
    text: "Vikings never actually wore horned ____.",
    answer: "Helmets",
  },
  {
    id: 199,
    text: "Cleopatra lived closer in time to the ____ than the Pyramids.",
    answer: "iPhone",
  },
  {
    id: 200,
    text: "The T-Rex lived closer in time to ____ than to the Stegosaurus.",
    answer: "Humans",
  },
  {
    id: 201,
    text: "Woolly Mammoths were still alive when the ____ were being built.",
    answer: "Pyramids",
  },
  {
    id: 202,
    text: "Tiffany & Co. is older than the country of ____.",
    answer: "Italy",
  },
  { id: 203, text: "Betty White was older than sliced ____.", answer: "Bread" },
  {
    id: 204,
    text: "Harvard University was founded before ____ was invented.",
    answer: "Calculus",
  },
  { id: 205, text: "Sharks have existed longer than ____.", answer: "Trees" },
  {
    id: 206,
    text: "The lighter was invented before the ____.",
    answer: "Match",
  },
  {
    id: 207,
    text: "The medical term for a 'brain freeze' is ____ ganglioneuralgia.",
    answer: "Sphenopalatine",
  },
  {
    id: 208,
    text: "The medical term for the struggle to get out of bed in the morning is ____.",
    answer: "Dysania",
  },
  {
    id: 209,
    text: "The act of throwing someone out of a window is called ____.",
    answer: "Defenestration",
  },
  {
    id: 210,
    text: "The 'flesh' of a strawberry is actually swollen ____ tissue.",
    answer: "Ovary",
  },
];
